/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class RolesRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.RolesRecord> {

	private static final long serialVersionUID = -1051825938;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setRoleId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Roles.ROLES.ROLE_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getRoleId() {
		return getValue(net.user1.union.zz.common.model.tables.Roles.ROLES.ROLE_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzuserRecord> fetchZzuserList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER)
			.where(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ROLE_ID.equal(getValue(net.user1.union.zz.common.model.tables.Roles.ROLES.ROLE_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setRoleName(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Roles.ROLES.ROLE_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getRoleName() {
		return getValue(net.user1.union.zz.common.model.tables.Roles.ROLES.ROLE_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Roles.ROLES.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Roles.ROLES.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Roles.ROLES.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Roles.ROLES.UPDATE_TIME);
	}

	/**
	 * Create a detached RolesRecord
	 */
	public RolesRecord() {
		super(net.user1.union.zz.common.model.tables.Roles.ROLES);
	}
}
