/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzgameusersummaryRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzgameusersummaryRecord> {

	private static final long serialVersionUID = -1001155024;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setUserSummaryId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_SUMMARY_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getUserSummaryId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_SUMMARY_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.zz_gameinsttemp_id]
	 * REFERENCES zzgameinsttempl [public.zzgameinsttempl.gameinsttempl_id]
	 * </pre></code>
	 */
	public void setZzGameinsttempId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.ZZ_GAMEINSTTEMP_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.zz_gameinsttemp_id]
	 * REFERENCES zzgameinsttempl [public.zzgameinsttempl.gameinsttempl_id]
	 * </pre></code>
	 */
	public java.lang.String getZzGameinsttempId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.ZZ_GAMEINSTTEMP_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.zz_gameinsttemp_id]
	 * REFERENCES zzgameinsttempl [public.zzgameinsttempl.gameinsttempl_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord fetchZzgameinsttempl() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL)
			.where(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.ZZ_GAMEINSTTEMP_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public void setUserId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public java.lang.String getUserId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzuserRecord fetchZzuser() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER)
			.where(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setTotalGamesPlayed(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.TOTAL_GAMES_PLAYED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getTotalGamesPlayed() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.TOTAL_GAMES_PLAYED);
	}

	/**
	 * An uncommented item
	 */
	public void setTotalGameWon(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.TOTAL_GAME_WON, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getTotalGameWon() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.TOTAL_GAME_WON);
	}

	/**
	 * An uncommented item
	 */
	public void setUserLevel(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_LEVEL, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getUserLevel() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_LEVEL);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.last_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public void setLastGameinstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.LAST_GAMEINST_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.last_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public java.lang.String getLastGameinstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.LAST_GAMEINST_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameusersummary.last_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameinstRecord fetchZzgameinst() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.LAST_GAMEINST_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setLastGameinstUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.LAST_GAMEINST_UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getLastGameinstUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.LAST_GAMEINST_UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setCurrentGameinstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.CURRENT_GAMEINST_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getCurrentGameinstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.CURRENT_GAMEINST_ID);
	}

	/**
	 * Create a detached ZzgameusersummaryRecord
	 */
	public ZzgameusersummaryRecord() {
		super(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY);
	}
}
