/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzgameinsttemplRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord> {

	private static final long serialVersionUID = 976848247;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setGameinsttemplId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getGameinsttemplId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameinstRecord> fetchZzgameinstList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_GAMEINSTTEMPL_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameusersummaryRecord> fetchZzgameusersummaryList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY)
			.where(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.ZZ_GAMEINSTTEMP_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameinsttempl.gameinsttempl_game_id]
	 * REFERENCES zzgame [public.zzgame.game_id]
	 * </pre></code>
	 */
	public void setGameinsttemplGameId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_GAME_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameinsttempl.gameinsttempl_game_id]
	 * REFERENCES zzgame [public.zzgame.game_id]
	 * </pre></code>
	 */
	public java.lang.String getGameinsttemplGameId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_GAME_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameinsttempl.gameinsttempl_game_id]
	 * REFERENCES zzgame [public.zzgame.game_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameRecord fetchZzgame() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME)
			.where(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.GAME_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_GAME_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setGameinsttemplGameDesc(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_GAME_DESC, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getGameinsttemplGameDesc() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_GAME_DESC);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum1(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM1, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum1() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM1);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum2(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM2, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum2() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM2);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum3(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM3, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum3() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM3);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum4(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM4, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum4() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM4);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum5(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM5, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum5() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM5);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum6(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM6, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum6() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM6);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum7(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM7, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum7() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM7);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum8(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM8, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum8() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM8);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum9(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM9, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum9() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM9);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamnum10(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM10, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameinstParamnum10() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMNUM10);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamdate1(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE1, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getGameinstParamdate1() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE1);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamdate2(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE2, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getGameinstParamdate2() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE2);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamdate3(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE3, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getGameinstParamdate3() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE3);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamdate4(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE4, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getGameinstParamdate4() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE4);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamdate5(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE5, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getGameinstParamdate5() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMDATE5);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamvar1(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR1, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getGameinstParamvar1() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR1);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamvar2(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR2, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getGameinstParamvar2() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR2);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamvar3(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR3, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getGameinstParamvar3() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR3);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamvar4(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR4, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getGameinstParamvar4() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR4);
	}

	/**
	 * An uncommented item
	 */
	public void setGameinstParamvar5(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR5, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getGameinstParamvar5() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINST_PARAMVAR5);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzgameinsttemplRecord
	 */
	public ZzgameinsttemplRecord() {
		super(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL);
	}
}
