/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrofiggroupRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofiggroupRecord> {

	private static final long serialVersionUID = 480694989;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlfiggroupId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlfiggroupId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrofigRecord> fetchZzzlrofigList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ZLFIGGROUP_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiggroupName(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZlfiggroupName() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiggroupNooffigrequired(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_NOOFFIGREQUIRED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfiggroupNooffigrequired() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_NOOFFIGREQUIRED);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrofiggroupRecord
	 */
	public ZzzlrofiggroupRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP);
	}
}
