/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrofigcoordRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofigcoordRecord> {

	private static final long serialVersionUID = -634850757;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlfigcoordId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlfigcoordId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofigcoord.zlfigcoord_zlfig_id]
	 * REFERENCES zzzlrofig [public.zzzlrofig.zlfig_id]
	 * </pre></code>
	 */
	public void setZlfigcoordZlfigId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_ZLFIG_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofigcoord.zlfigcoord_zlfig_id]
	 * REFERENCES zzzlrofig [public.zzzlrofig.zlfig_id]
	 * </pre></code>
	 */
	public java.lang.String getZlfigcoordZlfigId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_ZLFIG_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofigcoord.zlfigcoord_zlfig_id]
	 * REFERENCES zzzlrofig [public.zzzlrofig.zlfig_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzzlrofigRecord fetchZzzlrofig() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_ZLFIG_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setZlfigcoordPosx(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_POSX, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfigcoordPosx() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_POSX);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfigcoordPosy(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_POSY, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfigcoordPosy() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_POSY);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrofigcoordRecord
	 */
	public ZzzlrofigcoordRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD);
	}
}
