/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class AuthassignmentRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord> {

	private static final long serialVersionUID = -1673982831;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.authassignment.itemname]
	 * REFERENCES authitem [public.authitem.name]
	 * </pre></code>
	 */
	public void setItemname(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.ITEMNAME, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.authassignment.itemname]
	 * REFERENCES authitem [public.authitem.name]
	 * </pre></code>
	 */
	public java.lang.String getItemname() {
		return getValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.ITEMNAME);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.authassignment.itemname]
	 * REFERENCES authitem [public.authitem.name]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.AuthitemRecord fetchAuthitem() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM)
			.where(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.NAME.equal(getValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.ITEMNAME)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setUserid(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.USERID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getUserid() {
		return getValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.USERID);
	}

	/**
	 * An uncommented item
	 */
	public void setBizrule(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.BIZRULE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getBizrule() {
		return getValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.BIZRULE);
	}

	/**
	 * An uncommented item
	 */
	public void setData(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.DATA, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getData() {
		return getValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.DATA);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.UPDATE_TIME);
	}

	/**
	 * Create a detached AuthassignmentRecord
	 */
	public AuthassignmentRecord() {
		super(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT);
	}
}
