/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class AuthitemRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.AuthitemRecord> {

	private static final long serialVersionUID = -737540679;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setName(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.NAME, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getName() {
		return getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.NAME);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord> fetchAuthassignmentList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT)
			.where(net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT.ITEMNAME.equal(getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.NAME)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord> fetchAuthitemchildListByChild() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Authitemchild.AUTHITEMCHILD)
			.where(net.user1.union.zz.common.model.tables.Authitemchild.AUTHITEMCHILD.CHILD.equal(getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.NAME)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord> fetchAuthitemchildListByParent() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Authitemchild.AUTHITEMCHILD)
			.where(net.user1.union.zz.common.model.tables.Authitemchild.AUTHITEMCHILD.PARENT.equal(getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.NAME)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setType(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getType() {
		return getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setDescription(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.DESCRIPTION, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getDescription() {
		return getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.DESCRIPTION);
	}

	/**
	 * An uncommented item
	 */
	public void setBizrule(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.BIZRULE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getBizrule() {
		return getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.BIZRULE);
	}

	/**
	 * An uncommented item
	 */
	public void setData(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.DATA, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getData() {
		return getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.DATA);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM.UPDATE_TIME);
	}

	/**
	 * Create a detached AuthitemRecord
	 */
	public AuthitemRecord() {
		super(net.user1.union.zz.common.model.tables.Authitem.AUTHITEM);
	}
}
