/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzgameRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzgameRecord> {

	private static final long serialVersionUID = 2132807764;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setGameId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.GAME_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getGameId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.GAME_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameinstRecord> fetchZzgameinstList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_GAME_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.GAME_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord> fetchZzgameinsttemplList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL)
			.where(net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL.GAMEINSTTEMPL_GAME_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.GAME_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setGameName(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.GAME_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getGameName() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.GAME_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzgameRecord
	 */
	public ZzgameRecord() {
		super(net.user1.union.zz.common.model.tables.Zzgame.ZZGAME);
	}
}
