/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzgameseatRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord> {

	private static final long serialVersionUID = 1503270859;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setGameseatId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getGameseatId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord> fetchZzzlrogamebetList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET)
			.where(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_GAMESEAT_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord> fetchZzzlrogamescoreList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE)
			.where(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_GAMESEAT_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public void setGameseatUserId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_USER_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public java.lang.String getGameseatUserId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_USER_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzuserRecord fetchZzuser() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER)
			.where(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_USER_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public void setGameseatGameinstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_GAMEINST_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public java.lang.String getGameseatGameinstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_GAMEINST_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameinstRecord fetchZzgameinst() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_GAMEINST_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setGameseatCreatedat(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_CREATEDAT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getGameseatCreatedat() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_CREATEDAT);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setGameRank(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAME_RANK, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameRank() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAME_RANK);
	}

	/**
	 * An uncommented item
	 */
	public void setZzgameseatStatus(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.ZZGAMESEAT_STATUS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZzgameseatStatus() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.ZZGAMESEAT_STATUS);
	}

	/**
	 * An uncommented item
	 */
	public void setGameseatScore(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_SCORE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getGameseatScore() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_SCORE);
	}

	/**
	 * An uncommented item
	 */
	public void setGameseatStatusUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_STATUS_UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getGameseatStatusUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_STATUS_UPDATE_TIME);
	}

	/**
	 * Create a detached ZzgameseatRecord
	 */
	public ZzgameseatRecord() {
		super(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT);
	}
}
