/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzinvitefriendsRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord> {

	private static final long serialVersionUID = -820422756;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setFbid(java.lang.Long value) {
		setValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.FBID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getFbid() {
		return getValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.FBID);
	}

	/**
	 * An uncommented item
	 */
	public void setZzinvitefriendsStatus(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.ZZINVITEFRIENDS_STATUS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZzinvitefriendsStatus() {
		return getValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.ZZINVITEFRIENDS_STATUS);
	}

	/**
	 * An uncommented item
	 */
	public void setUserId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.USER_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS.USER_ID);
	}

	/**
	 * Create a detached ZzinvitefriendsRecord
	 */
	public ZzinvitefriendsRecord() {
		super(net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS);
	}
}
