/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzproductRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzproductRecord> {

	private static final long serialVersionUID = -667921997;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setProductId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getProductId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameinstRecord> fetchZzgameinstList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_PRODUCT_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setProductSku(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_SKU, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getProductSku() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_SKU);
	}

	/**
	 * An uncommented item
	 */
	public void setProductName(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getProductName() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setProductBrand(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_BRAND, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getProductBrand() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_BRAND);
	}

	/**
	 * An uncommented item
	 */
	public void setProductShortdesc(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_SHORTDESC, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getProductShortdesc() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_SHORTDESC);
	}

	/**
	 * An uncommented item
	 */
	public void setProductImagename(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_IMAGENAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getProductImagename() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_IMAGENAME);
	}

	/**
	 * An uncommented item
	 */
	public void setProductDesc(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_DESC, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getProductDesc() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_DESC);
	}

	/**
	 * An uncommented item
	 */
	public void setProductPrice(java.math.BigDecimal value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_PRICE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.math.BigDecimal getProductPrice() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.PRODUCT_PRICE);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzproductRecord
	 */
	public ZzproductRecord() {
		super(net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT);
	}
}
