/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzuserRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzuserRecord> {

	private static final long serialVersionUID = 242402052;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setUserId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getUserId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameinstRecord> fetchZzgameinstList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_CREATED_BY.equal(getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord> fetchZzgameseatList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT)
			.where(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_USER_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzgameusersummaryRecord> fetchZzgameusersummaryList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY)
			.where(net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY.USER_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord> fetchZzzlrofriendsList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS.USER_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setUserName(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserName() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setUserEmail(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_EMAIL, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserEmail() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_EMAIL);
	}

	/**
	 * An uncommented item
	 */
	public void setUserFbid(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_FBID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserFbid() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_FBID);
	}

	/**
	 * An uncommented item
	 */
	public void setUserPassword(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_PASSWORD, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserPassword() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_PASSWORD);
	}

	/**
	 * An uncommented item
	 */
	public void setUserHandle(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_HANDLE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserHandle() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_HANDLE);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzuser.user_role_id]
	 * REFERENCES roles [public.roles.role_id]
	 * </pre></code>
	 */
	public void setUserRoleId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ROLE_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzuser.user_role_id]
	 * REFERENCES roles [public.roles.role_id]
	 * </pre></code>
	 */
	public java.lang.String getUserRoleId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ROLE_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzuser.user_role_id]
	 * REFERENCES roles [public.roles.role_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.RolesRecord fetchRoles() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Roles.ROLES)
			.where(net.user1.union.zz.common.model.tables.Roles.ROLES.ROLE_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ROLE_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setUserFname(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_FNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserFname() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_FNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setUserLname(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_LNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUserLname() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_LNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setZzuserStatus(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.ZZUSER_STATUS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZzuserStatus() {
		return getValue(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.ZZUSER_STATUS);
	}

	/**
	 * Create a detached ZzuserRecord
	 */
	public ZzuserRecord() {
		super(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER);
	}
}
