/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrofiginstcoordRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord> {

	private static final long serialVersionUID = 334048093;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlfiginstcoordId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlfiginstcoordId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofiginstcoord.zlfiginstcoord_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public void setZlfiginstcoordZlfiginstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_ZLFIGINST_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofiginstcoord.zlfiginstcoord_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public java.lang.String getZlfiginstcoordZlfiginstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_ZLFIGINST_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofiginstcoord.zlfiginstcoord_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzzlrofiginstRecord fetchZzzlrofiginst() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_ZLFIGINST_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiginstcoordPosx(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_POSX, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfiginstcoordPosx() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_POSX);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiginstcoordPosy(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_POSY, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfiginstcoordPosy() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_POSY);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrofiginstcoordRecord
	 */
	public ZzzlrofiginstcoordRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD);
	}
}
