/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrofiginstRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstRecord> {

	private static final long serialVersionUID = 1928633991;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlfiginstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlfiginstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord> fetchZzzlrofiginstcoordList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD.ZLFIGINSTCOORD_ZLFIGINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord> fetchZzzlrogameinstfigList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG)
			.where(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_ZLFIGINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofiginst.zlfiginst_zlfig_id]
	 * REFERENCES zzzlrofig [public.zzzlrofig.zlfig_id]
	 * </pre></code>
	 */
	public void setZlfiginstZlfigId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ZLFIG_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofiginst.zlfiginst_zlfig_id]
	 * REFERENCES zzzlrofig [public.zzzlrofig.zlfig_id]
	 * </pre></code>
	 */
	public java.lang.String getZlfiginstZlfigId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ZLFIG_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofiginst.zlfiginst_zlfig_id]
	 * REFERENCES zzzlrofig [public.zzzlrofig.zlfig_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzzlrofigRecord fetchZzzlrofig() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ZLFIG_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiginstValid(java.lang.Short value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_VALID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Short getZlfiginstValid() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_VALID);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiginstNoofcolumns(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_NOOFCOLUMNS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfiginstNoofcolumns() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_NOOFCOLUMNS);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiginstNoofrows(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_NOOFROWS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfiginstNoofrows() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_NOOFROWS);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfiginstOrientation(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ORIENTATION, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZlfiginstOrientation() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ORIENTATION);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrofiginstRecord
	 */
	public ZzzlrofiginstRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST);
	}
}
