/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrogamebetRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord> {

	private static final long serialVersionUID = 605598066;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlgamebetId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlgamebetId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public void setZlgamebetZlgameroundId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_ZLGAMEROUND_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public java.lang.String getZlgamebetZlgameroundId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_ZLGAMEROUND_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzzlrogameroundRecord fetchZzzlrogameround() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND)
			.where(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_ZLGAMEROUND_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public void setZlgamebetGameseatId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_GAMESEAT_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public java.lang.String getZlgamebetGameseatId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_GAMESEAT_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameseatRecord fetchZzgameseat() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT)
			.where(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_GAMESEAT_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setZlgamebetBettime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_BETTIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getZlgamebetBettime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_BETTIME);
	}

	/**
	 * An uncommented item
	 */
	public void setZlgamebetBetcoord(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_BETCOORD, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlgamebetBetcoord() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_BETCOORD);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrogamebetRecord
	 */
	public ZzzlrogamebetRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET);
	}
}
