/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrofigRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofigRecord> {

	private static final long serialVersionUID = -379183831;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlfigId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlfigId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrofigcoordRecord> fetchZzzlrofigcoordList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD.ZLFIGCOORD_ZLFIG_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstRecord> fetchZzzlrofiginstList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ZLFIG_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setZlfigName(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZlfigName() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfigRequired(java.lang.Short value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_REQUIRED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Short getZlfigRequired() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_REQUIRED);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfigRemark(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_REMARK, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZlfigRemark() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_REMARK);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfigPoints(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_POINTS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfigPoints() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_POINTS);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofig.zlfig_zlfiggroup_id]
	 * REFERENCES zzzlrofiggroup [public.zzzlrofiggroup.zlfiggroup_id]
	 * </pre></code>
	 */
	public void setZlfigZlfiggroupId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ZLFIGGROUP_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofig.zlfig_zlfiggroup_id]
	 * REFERENCES zzzlrofiggroup [public.zzzlrofiggroup.zlfiggroup_id]
	 * </pre></code>
	 */
	public java.lang.String getZlfigZlfiggroupId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ZLFIGGROUP_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofig.zlfig_zlfiggroup_id]
	 * REFERENCES zzzlrofiggroup [public.zzzlrofiggroup.zlfiggroup_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzzlrofiggroupRecord fetchZzzlrofiggroup() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP.ZLFIGGROUP_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_ZLFIGGROUP_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setZlfigType(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlfigType() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG.ZLFIG_TYPE);
	}

	/**
	 * Create a detached ZzzlrofigRecord
	 */
	public ZzzlrofigRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG);
	}
}
