/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public final class Sequences {

	/**
	 * The sequence public.public.zalerio_sequence
	 */
	public static final org.jooq.Sequence<java.lang.Long> ZALERIO_SEQUENCE = new org.jooq.impl.SequenceImpl<java.lang.Long>("zalerio_sequence", net.user1.union.zz.common.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence public.public.zzinvitefriends_seq
	 */
	public static final org.jooq.Sequence<java.lang.Long> ZZINVITEFRIENDS_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("zzinvitefriends_seq", net.user1.union.zz.common.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * No instances
	 */
	private Sequences() {}
}
