/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1457387293;

	/**
	 * The singleton instance of public
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			net.user1.union.zz.common.model.Sequences.ZALERIO_SEQUENCE,
			net.user1.union.zz.common.model.Sequences.ZZINVITEFRIENDS_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT,
			net.user1.union.zz.common.model.tables.Authitem.AUTHITEM,
			net.user1.union.zz.common.model.tables.Authitemchild.AUTHITEMCHILD,
			net.user1.union.zz.common.model.tables.Roles.ROLES,
			net.user1.union.zz.common.model.tables.Zzcron.ZZCRON,
			net.user1.union.zz.common.model.tables.Zzgame.ZZGAME,
			net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST,
			net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL,
			net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT,
			net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY,
			net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS,
			net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT,
			net.user1.union.zz.common.model.tables.Zzuser.ZZUSER,
			net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG,
			net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD,
			net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP,
			net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST,
			net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD,
			net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS,
			net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET,
			net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG,
			net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND,
			net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE);
	}
}
