/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table public.authassignment
	 */
	public static net.user1.union.zz.common.model.tables.Authassignment AUTHASSIGNMENT = net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT;

	/**
	 * The table public.authitem
	 */
	public static net.user1.union.zz.common.model.tables.Authitem AUTHITEM = net.user1.union.zz.common.model.tables.Authitem.AUTHITEM;

	/**
	 * The table public.authitemchild
	 */
	public static net.user1.union.zz.common.model.tables.Authitemchild AUTHITEMCHILD = net.user1.union.zz.common.model.tables.Authitemchild.AUTHITEMCHILD;

	/**
	 * The table public.roles
	 */
	public static net.user1.union.zz.common.model.tables.Roles ROLES = net.user1.union.zz.common.model.tables.Roles.ROLES;

	/**
	 * The table public.zzcron
	 */
	public static net.user1.union.zz.common.model.tables.Zzcron ZZCRON = net.user1.union.zz.common.model.tables.Zzcron.ZZCRON;

	/**
	 * The table public.zzgame
	 */
	public static net.user1.union.zz.common.model.tables.Zzgame ZZGAME = net.user1.union.zz.common.model.tables.Zzgame.ZZGAME;

	/**
	 * The table public.zzgameinst
	 */
	public static net.user1.union.zz.common.model.tables.Zzgameinst ZZGAMEINST = net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST;

	/**
	 * The table public.zzgameinsttempl
	 */
	public static net.user1.union.zz.common.model.tables.Zzgameinsttempl ZZGAMEINSTTEMPL = net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL;

	/**
	 * The table public.zzgameseat
	 */
	public static net.user1.union.zz.common.model.tables.Zzgameseat ZZGAMESEAT = net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT;

	/**
	 * The table public.zzgameusersummary
	 */
	public static net.user1.union.zz.common.model.tables.Zzgameusersummary ZZGAMEUSERSUMMARY = net.user1.union.zz.common.model.tables.Zzgameusersummary.ZZGAMEUSERSUMMARY;

	/**
	 * The table public.zzinvitefriends
	 */
	public static net.user1.union.zz.common.model.tables.Zzinvitefriends ZZINVITEFRIENDS = net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS;

	/**
	 * The table public.zzproduct
	 */
	public static net.user1.union.zz.common.model.tables.Zzproduct ZZPRODUCT = net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT;

	/**
	 * The table public.zzuser
	 */
	public static net.user1.union.zz.common.model.tables.Zzuser ZZUSER = net.user1.union.zz.common.model.tables.Zzuser.ZZUSER;

	/**
	 * The table public.zzzlrofig
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrofig ZZZLROFIG = net.user1.union.zz.common.model.tables.Zzzlrofig.ZZZLROFIG;

	/**
	 * The table public.zzzlrofigcoord
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrofigcoord ZZZLROFIGCOORD = net.user1.union.zz.common.model.tables.Zzzlrofigcoord.ZZZLROFIGCOORD;

	/**
	 * The table public.zzzlrofiggroup
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrofiggroup ZZZLROFIGGROUP = net.user1.union.zz.common.model.tables.Zzzlrofiggroup.ZZZLROFIGGROUP;

	/**
	 * The table public.zzzlrofiginst
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrofiginst ZZZLROFIGINST = net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST;

	/**
	 * The table public.zzzlrofiginstcoord
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord ZZZLROFIGINSTCOORD = net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD;

	/**
	 * The table public.zzzlrofriends
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrofriends ZZZLROFRIENDS = net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS;

	/**
	 * The table public.zzzlrogamebet
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrogamebet ZZZLROGAMEBET = net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET;

	/**
	 * The table public.zzzlrogameinstfig
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrogameinstfig ZZZLROGAMEINSTFIG = net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG;

	/**
	 * The table public.zzzlrogameround
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrogameround ZZZLROGAMEROUND = net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND;

	/**
	 * The table public.zzzlrogamescore
	 */
	public static net.user1.union.zz.common.model.tables.Zzzlrogamescore ZZZLROGAMESCORE = net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE;

	/**
	 * No instances
	 */
	private Tables() {}
}
