// Generated by CoffeeScript 1.4.0

define(["../helper/utils"], function(utils) {
  var resignPopUP, resignme, sendResignToServer;
  resignPopUP = function() {
    return jQuery("#bottomHUDbuttons-more").click(function() {
      var currentUserObj, plrs, seatId, totalPlayer;
      totalPlayer = 0;
      plrs = zzGlobals.dataObjVars.AP.PLRS;
      for (seatId in plrs) {
        if (plrs[seatId].PRE === 0 ? plrs[seatId].GSS === 2 || plrs[seatId].GSS === 4 : void 0) {
          ++totalPlayer;
        }
      }
      currentUserObj = jQuery.parseJSON(zzGlobals.clientVars.UINFO);
      if (totalPlayer > 1 && parseInt(zzGlobals.roomVars.FR) !== 1 && parseInt(currentUserObj.PRE) !== 1) {
        jQuery(".resignPopup").show();
        return jQuery(".resignPopup").before("<div class=\"overlay\"></div>");
      }
    });
  };
  resignPopUP();
  sendResignToServer = function() {
    jQuery(".draggableBets").attr("draggable", "false");
    jQuery(".resignPopup").hide();
    jQuery(".overlay").remove();
    jQuery("#gameBetPanel").hide();
    return jDocument.trigger(zzEvents.SEND_UPC_MESSAGE, [UPC.SEND_ROOMMODULE_MESSAGE, zzGlobals.roomVars[zzGlobals.roomCodes.ROOM_ID], "RQ", "C|RG"]);
  };
  resignme = document.getElementById("resignme");
  return utils.addEventHandler(resignme, "click", sendResignToServer, false);
});
