// Generated by CoffeeScript 1.3.3

define([], function() {
  var showRoundScorePopup;
  showRoundScorePopup = function() {
    var i, index, rankHtml, roundPopupHeading, scoreArray, scorePopup, scorePopupContent, scorePopuptopthree, seatId, seatIdArray, selfHtml, selfHtmlImg, selfHtmlPoints, userCount, usersObject, x, _currentRoundStatus;
    if (zzGlobals.roomVars.CR.split("_")[1] === "0" || zzGlobals.roomVars.FR === "1") {
      return;
    }
    if (parseInt(zzGlobals.roomVars.CR.split("_")[1]) !== _currentRoundStatus) {
      _currentRoundStatus = parseInt(zzGlobals.roomVars.CR.split("_")[1]);
    } else {
      return;
    }
    usersObject = jQuery.parseJSON(zzGlobals.roomVars.AP);
    for (i in usersObject) {
      usersObject[i] = jQuery.parseJSON(usersObject[i]);
      usersObject[i].PLRS = jQuery.parseJSON(usersObject[i].PLRS);
      scoreArray = [];
      seatIdArray = [];
      for (seatId in usersObject[i].PLRS) {
        usersObject[i].PLRS[seatId] = jQuery.parseJSON(usersObject[i].PLRS[seatId]);
        scoreArray[seatId] = parseInt(usersObject[i].PLRS[seatId].PSC);
        seatIdArray.push(seatId);
      }
      seatIdArray.sort(function(x, y) {
        return scoreArray[y] - scoreArray[x];
      });
      usersObject[i].PLSC = {};
      for (x in seatIdArray) {
        usersObject[i].PLSC[x] = seatIdArray[x];
      }
    }
    usersObject = usersObject[i];
    scorePopup = document.createElement("div");
    scorePopup.className = "roundresult";
    scorePopupContent = document.createElement("div");
    scorePopupContent.className = "content_r bounceIn animated";
    scorePopuptopthree = document.createElement("div");
    scorePopuptopthree.className = "top_three_r";
    i = 0;
    rankHtml = "";
    userCount = 0;
    for (index in usersObject.PLSC) {
      seatId = usersObject.PLSC[index];
      if (parseInt(usersObject.PLRS[seatId].GSS) !== 2) {
        continue;
      }
      if (parseInt(usersObject.PLRS[seatId].PRE) === 1) {
        continue;
      }
      userCount++;
      if (userCount <= 3) {
        rankHtml += "<div class='score'><img src='https://graph.facebook.com/" + usersObject.PLRS[seatId].PFB + "/picture' /><div class='points plus'>" + usersObject.PLRS[seatId].PSC + "</div></div>";
      }
      if (zzGlobals.currentUserDBId === usersObject.PLRS[seatId].UI) {
        selfHtml = document.createElement("div");
        selfHtml.className = "score self";
        selfHtmlImg = document.createElement("img");
        selfHtmlImg.src = "https://graph.facebook.com/" + usersObject.PLRS[seatId].PFB + "/picture";
        selfHtmlPoints = document.createElement("div");
        selfHtmlPoints.className = "points plus";
        selfHtmlPoints.innerHTML = usersObject.PLRS[seatId].PSC;
        selfHtml.appendChild(selfHtmlImg);
        selfHtml.appendChild(selfHtmlPoints);
      }
    }
    jQuery(".roundresult").remove();
    jQuery(scorePopuptopthree).append(rankHtml);
    roundPopupHeading = document.createElement("h2");
    roundPopupHeading.id = "round_no_r";
    jQuery(roundPopupHeading).text("Round " + parseInt(zzGlobals.roomVars.CR.split("_")[1]));
    scorePopupContent.appendChild(roundPopupHeading);
    if (selfHtml) {
      scorePopupContent.appendChild(selfHtml);
      scorePopupContent.appendChild(scorePopuptopthree);
      scorePopup.appendChild(scorePopupContent);
      if (parseInt(zzGlobals.roomVars.CR.split("_")[1]) > 0) {
        $("#active-screen").append(scorePopup);
        setTimeout((function() {
          return $(".roundresult").remove();
        }), 5000);
        return $(".roundresult").click(function() {
          return $(this).remove();
        });
      }
    }
  };
  jDocument.bind("room:" + zzGlobals.roomCodes.ALL_PLAYER_INFO, showRoundScorePopup);
  return true;
});
