// Generated by CoffeeScript 1.4.0

define([], function() {
  var showFrndSelector;
  return showFrndSelector = function() {
    var boxBlank, fbUserData, tutorial;
    if (typeof tutorial !== 'undefined') {
      if (tutorial === true) {
        boxBlank = jQuery('.box-blank');
        boxBlank.text('');
        boxBlank.removeClass();
        boxBlank.addClass('box-blank box-black');
      }
    }
    tutorial = false;
    fbUserData = {};
    return FB.api({
      method: 'fql.query',
      query: "SELECT uid, name, pic_square, online_presence, username FROM user WHERE uid IN (SELECT uid2 FROM friend WHERE uid1 = me()) order by name"
    }, function(response) {
      var html, i, j, _i, _j, _len, _len1, _ref;
      for (_i = 0, _len = response.length; _i < _len; _i++) {
        i = response[_i];
        fbUserData((_ref = response([i]), i = _ref[0], _ref));
        html = '';
        for (_j = 0, _len1 = fbUserData.length; _j < _len1; _j++) {
          j = fbUserData[_j];
          html += '<div class="rep"><img src="' + fbUserData[j].pic_square + '" /><div>' + fbUserData[j].name + '<br/></div>';
          html += '<input type="button" style="display:none" value="' + fbUserData[j].uid + '" class="status" />';
          html += '<span class="' + fbUserData[j].online_presence + '">' + fbUserData[j].online_presence + '</span>';
          html += '<a class="select_button right">Select</a></div><div class="line"></div>';
        }
      }
      return $.ajax({
        type: 'POST',
        url: siteUrl + "/user/getFriend"
      }).done(function(data) {
        $('body').append(data);
        $("#floatingBarsG").css('display', 'none');
        $('.friendlist').html(html);
        if (playSound) {
          return popupapperence.play();
        }
      });
    });
  };
});
