// Generated by CoffeeScript 1.3.3

define([], function() {
  var showInviteStatus;
  showInviteStatus = function(currentGameUsersData) {
    var acceptedImgs, declinedImgs, gameObjPLRS, img, imgWrapper, invitedImgs, popupDiv, popupDivBase, popupDivClose, popupStatusBase, popupStatusWrapper, popupacceptBlock, popupbuttonWrapper, popupdeclineBlock, popupimgWrapper, popupinviteBlock, popupleftButton, popupleftButtonWrapper, popuprightButton, popuprightButtonWrapper, popuptextLeftButton, popuptextRightButton, popuptopUserInfo, rejected, spanTag, toShow, totalUser, userInfo, usersInfoObject, x, y, z;
    popupDivBase = document.createElement("div");
    popupDivBase.className = "status_show_popup zalerio_popup";
    popupDivBase.id = "invitestatus";
    popupDivBase.style.display = "block";
    popupDiv = document.createElement("div");
    popupDiv.id = "score_friendpopup";
    popupDiv.className = "outer_base";
    popupDivClose = document.createElement("a");
    popupDivClose.id = "close";
    popupDivClose.className = "positionAbsolute";
    popupDivClose.onclick = function() {
      jQuery('.status_show_popup').remove();
      return false;
    };
    popupStatusBase = document.createElement("div");
    popupStatusBase.className = "invite_status_base";
    popupStatusBase.style.paddingTop = "32px";
    popuptopUserInfo = document.createElement("div");
    popuptopUserInfo.className = "topUserInfo";
    popupStatusWrapper = document.createElement("div");
    popupStatusWrapper.className = "statusWrapper";
    popupacceptBlock = document.createElement("div");
    popupacceptBlock.className = "acceptBlock";
    popupinviteBlock = document.createElement("div");
    popupinviteBlock.className = "inviteBlock";
    popupdeclineBlock = document.createElement("div");
    popupdeclineBlock.className = "declineBlock";
    popupbuttonWrapper = document.createElement("div");
    popupbuttonWrapper.className = "buttonWrapper";
    popupleftButtonWrapper = document.createElement("div");
    popupleftButtonWrapper.className = "leftButtonWrapper";
    popupleftButton = document.createElement("div");
    popupleftButton.className = "leftButton";
    popupleftButton.innerHTML = "Close Invitations";
    popupleftButton.onclick = function() {
      return closeInvits();
    };
    popuptextLeftButton = document.createElement("div");
    popuptextLeftButton.className = "textLeftButton";
    popuptextLeftButton.innerHTML = "Game will kick-off with all friends that have accepted your game invitation so far";
    popuprightButtonWrapper = document.createElement("div");
    popuprightButtonWrapper.className = "rightButtonWrapper";
    popuprightButton = document.createElement("div");
    popuprightButton.className = "rightButton";
    popuprightButton.innerHTML = "Send Reminder";
    popuptextRightButton = document.createElement("div");
    popuptextRightButton.className = "textRightButton";
    popuptextRightButton.innerHTML = "Friends who did not respond yet will get a gentle reminder to join your game...";
    for (x in currentGameUsersData) {
      usersInfoObject = currentGameUsersData[x];
      totalUser = usersInfoObject.TP;
      toShow = usersInfoObject.GCB;
      gameObjPLRS = jQuery.parseJSON(usersInfoObject.PLRS);
      break;
    }
    invitedImgs = [];
    acceptedImgs = [];
    declinedImgs = [];
    rejected = [];
    for (y in gameObjPLRS) {
      userInfo = jQuery.parseJSON(gameObjPLRS[y]);
      if (parseInt(userInfo.GSS) === 1) {
        img = document.createElement("img");
        img.src = "https://graph.facebook.com/" + userInfo.PFB + "/picture";
        invitedImgs.push(img);
      } else if (parseInt(userInfo.GSS) === 2) {
        img = document.createElement("img");
        img.src = "https://graph.facebook.com/" + userInfo.PFB + "/picture";
        acceptedImgs.push(img);
      } else if (parseInt(userInfo.GSS) === 3) {
        img = document.createElement("img");
        img.src = "https://graph.facebook.com/" + userInfo.PFB + "/picture";
        declinedImgs.push(img);
      } else {
        rejected.push(userInfo.GSS);
      }
    }
    popupimgWrapper = document.createElement("div");
    popupimgWrapper.className = "imgWrapper";
    if (parseInt(toShow) !== parseInt(zzGlobals.currentUserDBId)) {
      return;
    }
    if (!(acceptedImgs.length + declinedImgs.length > totalUser / 2 && invitedImgs.length !== 0)) {
      return;
    }
    if (zzGlobals.inviteStatus !== null && typeof zzGlobals.inviteStatus !== "undefined") {
      if (!(rejected.length + acceptedImgs.length + declinedImgs.length > zzGlobals.inviteStatus)) {
        return;
      }
    }
    zzGlobals.inviteStatus = rejected.length + acceptedImgs.length + declinedImgs.length;
    if (acceptedImgs.length !== 0) {
      imgWrapper = document.createElement("div");
      imgWrapper.className = "imgWrapper";
      spanTag = document.createElement("span");
      spanTag.innerHTML = "Accepted";
      for (z in acceptedImgs) {
        imgWrapper.appendChild(acceptedImgs[z]);
      }
      popupacceptBlock.appendChild(spanTag);
      popupacceptBlock.appendChild(imgWrapper);
    }
    if (declinedImgs.length !== 0) {
      imgWrapper = document.createElement("div");
      imgWrapper.className = "imgWrapper";
      spanTag = document.createElement("span");
      spanTag.innerHTML = "Declined";
      for (z in declinedImgs) {
        imgWrapper.appendChild(declinedImgs);
      }
      popupdeclineBlock.appendChild(spanTag);
      popupdeclineBlock.appendChild(imgWrapper);
    }
    if (invitedImgs.length !== 0) {
      imgWrapper = document.createElement("div");
      imgWrapper.className = "imgWrapper";
      spanTag = document.createElement("span");
      spanTag.innerHTML = "Not responded yet ...";
      for (z in invitedImgs) {
        console.log("invitedImgs", invitedImgs);
        imgWrapper.appendChild(invitedImgs[z]);
      }
      popupinviteBlock.appendChild(spanTag);
      popupinviteBlock.appendChild(imgWrapper);
    }
    popupStatusWrapper.appendChild(popupacceptBlock);
    popupStatusWrapper.appendChild(popupdeclineBlock);
    popupStatusWrapper.appendChild(popupinviteBlock);
    popupStatusBase.appendChild(popuptopUserInfo);
    popupStatusBase.appendChild(popupStatusWrapper);
    popupleftButtonWrapper.appendChild(popupleftButton);
    popupleftButtonWrapper.appendChild(popuptextLeftButton);
    popuprightButtonWrapper.appendChild(popuprightButton);
    popuprightButtonWrapper.appendChild(popuptextRightButton);
    popupbuttonWrapper.appendChild(popupleftButtonWrapper);
    popupbuttonWrapper.appendChild(popuprightButtonWrapper);
    popupStatusBase.appendChild(popupbuttonWrapper);
    popupDiv.appendChild(popupDivClose);
    popupDiv.appendChild(popupStatusBase);
    popupDivBase.appendChild(popupDiv);
    jQuery('.status_show_popup').remove();
    return jQuery("body").append(popupDivBase);
  };
  jDocument.bind("dataObj:" + zzGlobals.dataObjCodes.ALL_PLAYER_INFO, showInviteStatus);
  return true;
});
