// Generated by CoffeeScript 1.3.3

define([], function() {
  var bindStatus;
  bindStatus = false;
  return $('.draggableBets').live("mouseover", function() {
    if (window.tutorialFlag) {
      return;
    }
    $('.draggableBets').draggable({
      start: function(e, ui) {
        $('.box-newBet').droppable("disable");
        $('.box-previousRoundCurrentPlayerIncorrect').droppable("disable");
        return $('.box-previousRoundCurrentPlayerCorrect').droppable("disable");
      },
      scope: "drop_tile",
      revert: 'invalid'
    });
    $('.box-blank').draggable({
      scope: "drop_tile",
      start: function(e, ui) {
        $('.box-newBet').droppable("disable");
        $('.box-previousRoundCurrentPlayerIncorrect').droppable("disable");
        return $('.box-previousRoundCurrentPlayerCorrect').droppable("disable");
      },
      revert: 'invalid',
      helper: 'clone'
    });
    if (bindStatus === false) {
      bindStatus = true;
      $('.box-blank').draggable("disable");
    }
    return $('.box-blank').droppable({
      scope: "drop_tile",
      drop: function(e, ui) {
        if (!ui.draggable.hasClass('box-blank')) {
          ui.draggable.remove();
        } else {
          ui.draggable.draggable("disable");
          ui.draggable.droppable("enable");
        }
        $(this).droppable("disabled");
        window.handleDropNew(e, ui);
        $(this).draggable("enable");
        return true;
      }
    }, true);
  });
});
