// Generated by CoffeeScript 1.3.3

define(["../../config/config", "./carouselView", "./animation"], function(config, carouselView, animation) {
  var crouselObjSize, updateLeftHud, updatePlayerPlate;
  updatePlayerPlate = function() {
    var currentUserLevel, currentUserObj;
    currentUserObj = jQuery.parseJSON(zzGlobals.clientVars.UINFO);
    if (isDevEnvironment) {
      console.log("Player Plate : ", currentUserObj);
    }
    jQuery("#currentUserName").text(currentUserObj.PDN);
    if (typeof currentUserObj.PL !== "undefined") {
      if (parseInt(currentUserObj.PL) === 0) {
        currentUserObj.PL = 1;
      }
      currentUserLevel = document.createElement("img");
      currentUserLevel.className = "userlevelbelt";
      currentUserLevel.src = baseUrl + "/images/zalerio_1.2/4.ingame_ui/carauselbelts_main_player/" + config.userLevelImgBig[parseInt(currentUserObj.PL) - 1];
      jQuery("#currentUserAreaImg .userlevelbelt").remove();
      return jQuery("#currentUserAreaImg").prepend(currentUserLevel);
    }
  };
  updateLeftHud = function() {
    var i, userPanelMov, usersInfoObject, usersObject;
    usersObject = jQuery.parseJSON(zzGlobals.roomVars.AP);
    console.log("All Users Data (zzGlobals.roomVars.AP)", usersObject);
    for (i in usersObject) {
      usersInfoObject = jQuery.parseJSON(usersObject[i]);
      break;
    }
    carouselView.drawCarousel(usersInfoObject, "userTopPicHUDMain", i, "usercrousel");
    userPanelMov = new animation.UserPanelMov(jQuery("#userTopPicHUDMain"), null, null, null, crouselObjSize(jQuery.parseJSON(usersInfoObject.PLRS)));
    jQuery("#navCarouselRight").unbind('click').click(function() {
      return userPanelMov.move("RIGHT", panelMoveMagnitudeCodes.ONE);
    });
    return jQuery("#navCarouselLeft").unbind('click').click(function() {
      return userPanelMov.move("LEFT", panelMoveMagnitudeCodes.ONE);
    });
  };
  crouselObjSize = function(obj) {
    var key, size, userObject;
    size = 0;
    for (key in obj) {
      userObject = jQuery.parseJSON(obj[key]);
      if (userObject.GSS === 3 || userObject.GSS === 5) {
        continue;
      }
      if (obj.hasOwnProperty(key)) {
        size++;
      }
    }
    return size;
  };
  jDocument.bind("room:" + zzGlobals.roomCodes.ALL_PLAYER_INFO, updateLeftHud);
  jDocument.bind("client:" + zzGlobals.clientCodes.USERINFO, updatePlayerPlate);
  return true;
});
