// Generated by CoffeeScript 1.3.3

define(["../../helper/confirmBox", "../../helper/utils", "gamePlayView"], function(confirmBox, utils, gamePlayView) {
  window.messageListener = function(event, messageName, broadcastType, fromClientID, roomID, message) {
    var i, playerBetTiles, playerBetsChangeObj, tileId;
    switch (messageName) {
      case zalerioCMDListners.BET_CHANGES:
        window.betChangeVOs = {};
        playerBetsChangeObj = jQuery.parseJSON(message);
        utils.log("zalerioCMDListners.BET_CHANGES : ", playerBetsChangeObj);
        window.currentBets = {};
        window.currentBetsIdx = {};
        for (i in playerBetsChangeObj) {
          if (i === "PB") {
            playerBetTiles = jQuery.parseJSON(playerBetsChangeObj[i]);
            for (tileId in playerBetTiles) {
              betChangeVOs[tileId] = playerBetTiles[tileId];
            }
          }
        }
        window.currentRoundBidPlaced = playerBetsChangeObj["BC"];
        return jDocument.trigger(zzEvents.CLIENT_BETS_PLACED, window.currentRoundBidPlaced);
    }
  };
  jDocument.bind(zzEvents.SERVER_MESSAGE, window.messageListener);
  return true;
});
