// Generated by CoffeeScript 1.3.3
define([],function(){
	isDevEnvironment = true;
	try{
	// global var which will contain user info
	var GB_UINFO = {};
	GB_UINFO.PFN = "";
}catch(err){}

/***** users record ***/
/**this function updates the stats popup - mygames and mylevel */
return function usersRecord(gameRecords)
{
	console.log("gameRecords",gameRecords);
	
   try
   {
    var is_apg = true;
    
  
    // APG hols the data about all past games    
    if(gameRecords.APG == 'ALL_PAST_GAME' || gameRecords.APG =='' || gameRecords.APG == null || typeof(gameRecords.APG) == 'undefined')
        {
            var APG = {};is_apg = false;
        }
        else
        {
            var APG = gameRecords.APG;
        }
   if (typeof(gameRecords.UINFO) == 'undefined' ){
       return;
   }
   // this variable holds user info     
   var UINFO = gameRecords.UINFO;
   GB_UINFO = UINFO;
    if ( typeof(UINFO.PL) == 'undefined' || parseInt(UINFO.PL) == 0){
            UINFO.PL = 1;
    }

   UINFO.user_pic = "https://graph.facebook.com/"+UINFO.PFB+ "/picture?type=square";
   // current user id
   var cuid = UINFO.UI;
   //this array will hold all the data about past games and user info
   var pastGames = {'won':{},'lost':{},'usersInfo':{}};
    
   var cm_fbids = "";
   var gssCount = 0; 
   }
   catch(err)
   {
       if(isDevEnvironment === true)
       {
           console.log('building past games data',err);
       }
       return;
   }
   
  try
  {
    for(i in APG)
        {
            // here i corresponds to gameid
            // gameData will hold the about a particular game
            var gameData = APG[i];
            for(j in gameData)
                {
                    // if key equals PLRS, then corresponding value array will hold the data about players 
                    if(j == 'PLRS')
                        {
                            var PLRS = gameData[j];
                            var has_won = 0;
                            user_arr = {};
                            for(seatid in PLRS)
                                {
                                    pldata = PLRS[seatid];
                                    if(pldata['UI'] == cuid && pldata['PR'] == 1){has_won = 1;}
                                    user_arr[pldata['UI']] = {};
                                    user_arr[pldata['UI']]['fbid']= pldata['PFB'];
                                    user_arr[pldata['UI']]['pre']= pldata['PRE'];
                                    user_arr[pldata['UI']]['gss']= pldata['GSS'];
                                    pastGames['usersInfo'][pldata['UI']] = {};
                                    pastGames['usersInfo'][pldata['UI']]['name'] = pldata['PDN'];
                                    pastGames['usersInfo'][pldata['UI']]['fbid'] = pldata['PFB'];
                                    pastGames['usersInfo'][pldata['UI']]['gss'] = pldata['GSS'];
                                    pastGames[i] = {};
                                    pastGames[i]['user_arr'] = user_arr;
                                }
                                if(has_won == 1)
                                    {
                                        pastGames[i]['won'] = 1; 
                                    }
                                    else
                                        {
                                            pastGames[i]['won'] = 0; 
                                        }
                                
                        }
                    
                }
        }
  }
  catch(err)
  {
      if(isDevEnvironment === true)
       {
                      console.log('building past games data',err);
       }
  }
          /***** RH will contain active ganmes data *****/
          try
          {
            if(typeof(gameRecords.RH) == 'object')
            {
               jQuery.each(gameRecords.RH,
                            function(gameId,gameData)
                            { 
                              jQuery("#active_rh_"+gameId).remove();  
                              if(gameData.GS != '0')
                              { 
                               var div_rip  = document.createElement("div");
                               div_rip.className = "rip";
                               div_rip.setAttribute('id','active_rh_'+gameId);
                               var div_caro  = document.createElement("div");
                               div_caro.className = "game_stats_user infiniteCarousel";
                               
                               
                               var div_wrapper  = document.createElement("div");
                               div_wrapper.className = "wrapper";
                               
                               var ul  = document.createElement("ul");
                               
                                
                                var pl_rank = '';
                                jQuery.each(gameData.PLRS,function(index,eachPL)
                                    { 
                                        var li  = document.createElement("li");
                                        var img  = document.createElement("img");
                                        var span  = document.createElement("span");
										var a = document.createElement("a");
                                        span.innerHTML=eachPL.PDN;
                                        img.setAttribute('width','31');
                                        img.setAttribute('height','31');
                                        img.setAttribute('src',"https://graph.facebook.com/"+ eachPL.PFB+ "/picture?type=square");
										a.setAttribute('href','#');
                                        a.appendChild(img);a.appendChild(span);li.appendChild(a);
                                       ul.appendChild(li);
                                       
                                       if(UINFO.PFB == eachPL.PFB){pl_rank = eachPL.PR};
                                    }
                                );
                                 
                                 div_wrapper.appendChild(ul);
                                 div_caro.appendChild(div_wrapper);
                                 
                                 
                                 
                                  var div_round_stats  = document.createElement("div");
                                  div_round_stats.className = 'round_stats';
                                  if(gameData.CR == 'F')
                                  {
                                      div_round_stats.innerHTML = gameData.CR;
                                  }
                                  else
                                  {    
                                    div_round_stats.innerHTML = getOrdinal(gameData.CR,true);
                                  }
                                  var div_rank_stats  = document.createElement("div");
                                  div_rank_stats.className = 'rank_stats';
                                  if(pl_rank != 0 && pl_rank != '' && pl_rank != ' ')
                                  {    
                                    div_rank_stats.innerHTML = getOrdinal(pl_rank,true);
                                  }else
                                      {
                                          div_rank_stats.innerHTML = '-';
                                      }
                                  div_rip.appendChild(div_caro);
                                  div_rip.appendChild(div_round_stats);
                                  div_rip.appendChild(div_rank_stats);
                                 
                                   jQuery("#rip_active_rh").append(div_rip);
								   
                                }
                                
                            }
                           );
                    }         
          }
          catch(err)
          {
              if(isDevEnvironment === true)
                  {
                      console.log('stats RH active games',err);
                  }
          }
          
          
          
     // show past games data
     try
     {
          // if data of all past games has changed
          if(is_apg)
          {
                // first remove the data of all past games that are present and rebuild with start
                jQuery(".ap_games").remove(); console.log('past',pastGames);
                jQuery.each(gameRecords.APG_SORT,
                            function(index,value)
                            {
                                // value is gameId
                                var div_rip  = document.createElement("div");
                                div_rip.className = 'rip ap_games';
                                
                               var div_caro  = document.createElement("div");
                                div_caro.className = 'game_stats_user infiniteCarousel';
                                
                                var div_wrapper  = document.createElement("div");
                                div_wrapper.className = 'wrapper';
                             
                                var ul  = document.createElement("ul");   
                                jQuery.each(pastGames[value]['user_arr'],function(uid,value)
                                    { 
                                        var li  = document.createElement("li");
                                        var img  = document.createElement("img");
                                        var span  = document.createElement("span");
                                        var a = document.createElement("a");
                                        span.innerHTML = pastGames['usersInfo'][uid]['name'];
                                        img.setAttribute('width','31');
                                        img.setAttribute('height','31');
                                        img.setAttribute('src',"https://graph.facebook.com/"+ pastGames['usersInfo'][uid]['fbid']+ "/picture?type=square");
					a.setAttribute('href','#');
                                        a.appendChild(img);a.appendChild(span);li.appendChild(a);
                                        ul.appendChild(li);
                                    }
                                );
                                    div_wrapper.appendChild(ul);
                                    div_caro.appendChild(div_wrapper);
                                    cm_fbids = "'";gssCount = 0;
                                    for(key in pastGames[value]['user_arr'])
                                    {
                                            if(pastGames[value]['user_arr'][key].gss =='2')
                                            {
                                                if(cm_fbids == "'")
                                                    {
                                                        cm_fbids +=pastGames[value]['user_arr'][key].fbid; 
                                                    }
                                                    else{cm_fbids +=","+pastGames[value]['user_arr'][key].fbid;}
                                                    gssCount += 1;
                                            }   
                                    }
                                   cm_fbids += "'"; 
                                    var div_medal  = document.createElement("div");
                                    div_medal.className = 'medal';
                                    var div_rematch  = document.createElement("div");
                                    div_rematch.className = 'rematch';
                                    if(gssCount > 1 && typeof pastGames[value]['user_arr'][UINFO.UI] != 'undefined' && pastGames[value]['user_arr'][UINFO.UI].pre == 0 )
                                    {    
                                        div_rematch.innerHTML =  '<a href="#" onclick="rematchPastGames('+cm_fbids+','+"'Rematch','"+value+"'"+'); return false;">Rematch</a>';
                                    }
				if(pastGames[value]['won'] == 1)
				{
                                    var img_medal  = document.createElement("img"); 
                                    img_medal.setAttribute('width','40');
                                    img_medal.setAttribute('height','31');
                                    img_medal.setAttribute('src',baseUrl+'/images/zalerio_1.2/5.all_popup/mystats/mygames/cup.png');
                                    div_medal.appendChild(img_medal);
				}
                                    div_rip.appendChild(div_caro);
                                    div_rip.appendChild(div_medal);
                                    div_rip.appendChild(div_rematch);
                                
                                    jQuery("#rip_won_apg").append(div_rip);
                            }
                    );
                        
                     
              }
     }
     catch(err)
     {
         if(isDevEnvironment === true)
                  {
                      console.log('showing past games',err);
                  }
     }
               /**** for scroll bar ******/
                jQuery(function()
			{ 
				jQuery('.scroll-pane').jScrollPane({showArrows: true,autoReinitialise: true});

			});
                        jQuery(".carousel_link").remove();
                  $('.infiniteCarousel').infiniteCarousel();
              
        // show level data
        try
        {
              var user_level = UINFO.PL;
              var cls = belt_array[user_level].toLowerCase();
              var top_level = sizeOfObj(belt_array);
              if(user_level < top_level)
              {
               var next_level = user_level+1;
                }
                else{
                    var next_level = user_level; 
                }
              var next_cls = belt_array[next_level].toLowerCase();
              var low_next_won_arr = total_won_array[next_level-1].split('-');
              var need_won_next = low_next_won_arr[0] - UINFO.GW;
             
              var low_next_game_arr = total_games_array[next_level-1].split('-');
              var need_game_next = low_next_game_arr[0] - UINFO.GP;
              
              // cr_belt_html will hold the data of current belt level like played games and won games till now
              var cr_belt_html = "<li>You played "+UINFO.GP+" game";
              if(UINFO.GP > 0){cr_belt_html +="s";}
              cr_belt_html += "</li><li>You won "+UINFO.GW+"</li>";
              
              //next_belt_html will hold the data, user need to complete like need t play 10 games and need to win 3 games to reach next level
              var next_belt_html ="";
              if(need_game_next > 0 && need_game_next > need_won_next)
                  {
                      next_belt_html +="<li>"+ need_game_next + " more game";
                      if(need_game_next > 1){next_belt_html +="s";}
                      next_belt_html +="</li>";
                  }
              if(need_won_next > 0 )
                  {
                      next_belt_html +="<li>"+ need_won_next + " more to win</li>";
                      
                  }
              
              jQuery("#next_belt_ul").html(next_belt_html);
              jQuery("#current_belt_ul").html(cr_belt_html);
              
              jQuery("#current_belt_h4").html(capFirst(cls));
              jQuery("#next_belt_h4").html(capFirst(next_cls));
              
              jQuery("#belt-info").attr('class','belt-info '+cls);
              jQuery("#belt-info").css('background','url('+baseUrl+'/images/zalerio_1.2/5.all_popup/mystats/mylevel/girl/girl_in'+cls+'/girl_'+cls+'_1.png) no-repeat -20px 33px');
              jQuery("#belt_text").html(capFirst(cls));
              if(user_level == next_level)
              {jQuery("#belt-info .next-belt").hide();jQuery("#belt-info .dummy_div").show();}
              else{jQuery("#belt-info .next-belt").show();jQuery("#belt-info .dummy_div").hide();}
              
              var vertical_text = "";
              // this will add all belts and the highlighted belt according to user level on right side of my level pop up
              for(i=top_level;i>0;i--)
                  {
                      var cl = belt_array[i].toLowerCase();
                      var cl_up = capFirst(cl);
                      if(user_level == i)
                          {
                              vertical_text += '<li class="active"><img src="../images/zalerio_1.2/5.all_popup/mystats/mylevel/belts/belts_highlighted/'+cl+'.png" alt="Black belt"><a class="'+cl+'" >'+cl_up+'</a></li>';
                          }else
                              {
                                  vertical_text += '<li><img src="../images/zalerio_1.2/5.all_popup/mystats/mylevel/belts/belts_ideal/'+cl+'.png" alt="Black belt"><a class="'+cl+'" >'+cl_up+'</a></li>';
                              }
                  }
              jQuery("#vertical_belt_conent").html(vertical_text);
               // show mylevel-check
                    jQuery("#mylevel-check").show();
    }
    catch(err)
    {
        if(isDevEnvironment === true)
        {
           console.log('showing level data',err);
        }
    }
    
    try
    {
        
    
                /*** user info that is displayed on top of my games and my level tabs ****/
                    jQuery("#stat_image_main").attr('src',UINFO.user_pic);
                    jQuery("#stat_image_tri_level").attr('src',baseUrl+"/images/zalerio_1.2/5.all_popup/mystats/mystatsCommon/stats_main_player_belts/"+userLevelImgBig[UINFO.PL-1]);
                    jQuery("#popup-stats .div_top .div_img #stat_userName").html(UINFO.PDN);
                    jQuery("#popup-stats .div_top #joined_time").html(" "+UINFO.JD);
                    //jQuery("#frnd_playing").html(obj.frnd_stats.on_zl);
                    //jQuery("#frnd_total").html(obj.frnd_stats.total - obj.frnd_stats.on_zl);
                    jQuery("#user-level-span").removeClass().addClass(capFirst(cls.toLowerCase())+'Belt').html(capFirst(cls.toLowerCase())+' Belt');
                   
    }
    catch(err)
    {
        if(isDevEnvironment === true)
        {
           console.log('showing stats top data',err);
        }
    }
                    
}
});