// Generated by CoffeeScript 1.4.0

define(["../../config/config", "../../helper/notifications"], function(config, notifications) {
  var updateRightHud;
  updateRightHud = function(event, message) {
    var acceptDecline, bindClick, gameId, gameSeatID, index, status, urDiv, urDivClassName;
    for (gameId in message) {
      if (window.secondArrow === '0') {
        window.secondArrow = gameId;
      }
      if (document.getElementById("right_hud_" + gameId) === null) {
        urDivClassName = gameInstId === gameId ? "userArea selected" : "userArea";
        urDiv = $("<div class=\"" + urDivClassName + "\" id=\"right_hud_" + gameId + "\" ></div>");
        if (message[gameId].CR) {
          urDiv.append("<div class=\"round_no\">" + message[gameId].CR + "</div>");
        }
        if (message[gameId].SD) {
          urDiv.append("<div class=\"game_end_time\">" + message[gameId].SD + "</div>");
        }
        for (index in message[gameId].PLSC) {
          gameSeatID = message[gameId].PLSC[index];
          if (message[gameId].PLRS[gameSeatID].GSS === 5 || message[gameId].PLRS[gameSeatID].GSS === 3) {
            continue;
          }
          status = message[gameId].PLRS[gameSeatID].PON === 1 ? "online" : "offline";
          if (message[gameId].PLRS[gameSeatID].PFB) {
            urDiv.append("<div class=\"imageWrapper\" id=\"right_hud_Images" + gameId + "\"><img src=\"https://graph.facebook.com/" + message[gameId].PLRS[gameSeatID].PFB + "/picture\" alt=\"" + message[gameId].PLRS[gameSeatID].PFN + "\" class=\"" + status + "\" id=\"who_am_i_" + gameSeatID + "\" /></div>");
          }
          if (message[gameId].PLRS[gameSeatID].GSS) {
            if (message[gameId].PLRS[gameSeatID].GSS === 1 && zzGlobals.currentUserDBId === message[gameId].PLRS[gameSeatID].UI) {
              acceptDecline = $("<div class=\"accept_decline\" id=\"accept_decline_" + gameId + "\"><div class=\"right_hud_accept\">Accept</div><div class=\"right_hud_decline\">Decline</div></div>");
              acceptInvitationAdd($(".right_hud_accept", acceptDecline), gameId);
              $(".right_hud_decline", acceptDecline).click({
                gsID: gameSeatID,
                id: gameId
              }, function(e) {
                return jDocument.trigger("sendDeclinedToServer", [e.data.gsID, e.data.id]);
              });
              urDiv.append(acceptDecline);
            } else if (zzGlobals.currentUserDBId === message[gameId].PLRS[gameSeatID].UI) {
              urDiv.click({
                id: gameId
              }, function(e) {
                sound.playSelectButtonSound();
                createGameDetailsPopup(e.data.id);
              });
            }
          }
          if (parseInt(message[gameId].GS) === 1) {
            $('#rightHUD-yourturn').append(urDiv);
          }
          if (parseInt(message[gameId].GS) === 2) {
            $('#rightHUD-theirturn').append(urDiv);
          }
        }
      } else {
        if (parseInt(message[gameId].GS) === 0) {
          jQuery("#right_hud_" + gameId).remove();
          continue;
        } else {
          if (parseInt(message[gameId].GS) === 1) {
            if (jQuery("#right_hud_" + gameId).parent().attr('id') === 'rightHUD-theirturn') {
              $("#right_hud_" + gameId).detach().appendTo('#rightHUD-yourturn');
            }
          } else if (parseInt(message[gameId].GS) === 2) {
            if ($("#right_hud_" + gameId).parent().attr('id') === 'rightHUD-yourturn') {
              $("#right_hud_" + gameId).detach().appendTo('#rightHUD-theirturn');
            }
          }
          if (message[gameId].CR) {
            $("#right_hud_" + gameId).find('.round_no').text(message[gameId].CR);
          }
          if (message[gameId].SD) {
            $("#right_hud_" + gameId).find('.game_end_time').html(message[gameId].SD);
          }
          for (gameSeatID in message[gameId].PLRS) {
            if (typeof message[gameId].PLRS[gameSeatID].PON !== "undefined") {
              if (message[gameId].PLRS[gameSeatID].GSS === 5 || message[gameId].PLRS[gameSeatID].GSS === 3) {
                $("#who_am_i_" + gameSeatID).remove();
              } else {
                $("#who_am_i_" + gameSeatID).removeClass().addClass(message[gameId].PLRS[gameSeatID].PON === 1 ? "online" : "offline");
              }
            }
            if (typeof message[gameId].PLRS[gameSeatID].GSS !== 'undefined') {
              if (message[gameId].PLRS[gameSeatID].GSS !== 1 && zzGlobals.currentUserDBId === message[gameId].PLRS[gameSeatID].UI) {
                $('#accept_decline_' + gameId).remove();
                bindClick = true;
                try {
                  if ($("#right_hud_" + gameId).data("events").click) {
                    bindClick = false;
                  }
                } catch (_error) {}
                if (bindClick) {
                  $("#right_hud_" + gameId).click({
                    id: gameId
                  }, function(e) {
                    sound.playSelectButtonSound();
                    return createGameDetailsPopup(e.data.id);
                  });
                }
              }
            }
          }
        }
      }
    }
    if ($('#rightHUD-yourturn').find(".userArea").length === 0) {
      if ($('#rightHUD-yourturn').find(".newCarouselblanktile").length === 0) {
        $('#rightHUD-yourturn').append('<div class="newCarouselblanktile"></div>');
      }
    } else {
      $("#rightHUD-yourturn .newCarouselblanktile").remove();
    }
    if ($('#rightHUD-theirturn').find(".userArea").length === 0) {
      if ($('#rightHUD-theirturn').find(".newCarouselblanktile").length === 0) {
        $('#rightHUD-theirturn').append('<div class="newCarouselblanktile"></div>');
      }
    } else {
      $("#rightHUD-theirturn .newCarouselblanktile").remove();
    }
    return true;
  };
  window.createGameDetailsPopup = function(gameId) {
    var betPlacedNoClass, el, gameDetails, gdAllRoundDiv, gdDiv, gdPlaydivClassName, gdUserImgclassName, i, index, lastEl, lastRoundId, playerName, plrs, remindUsersData, roundId, trClass, _i, _ref, _score;
    gameDetails = zzGlobals.msgVars.RH[gameId];
    jQuery('.gdWrapper').remove();
    gdAllRoundDiv = document.createElement("div");
    gdAllRoundDiv.className = 'gdAllRoundDiv';
    gdAllRoundDiv.id = 'gdAllRoundDivId';
    drawRoundsPanel(gdAllRoundDiv);
    try {
      for (roundId = _i = 1; _i <= 7; roundId = ++_i) {
        el = roundVOsIdxRightHUD[roundId];
        if (roundId > parseInt(gameDetails.CR)) {
          el.className = "notPlayedRound";
        } else {
          el.className = "doneRound";
        }
        if (roundId === parseInt(gameDetails.CR)) {
          el.className = "currentRound";
        }
        lastEl = el;
        lastRoundId = roundId;
      }
      if (lastEl && lastRoundId) {
        if (lastRoundId === parseInt(gameDetails.CR)) {
          lastEl.className = "currentFinalRound";
        } else {
          lastEl.className = "finalRound";
        }
      }
    } catch (_error) {}
    gdDiv = $("<div class=\"gdWrapper animated fadeInRight\">\n	<div class=\"gdScoreCardDiv\">\n		<div class=\"gdScoreInfoDiv\">\n			<table class=\"gdScoreCardTbl\"></table>\n		</div>\n	</div>\n	<div class=\"gdUsersImgdiv\"></div>\n	<div class=\"gdReminddiv\"></div>\n	<div class=\"gdReturndiv\"></div>\n</div>");
    $('.gdScoreInfoDiv', gdDiv).before($(gdAllRoundDiv));
    $('.gdReturndiv', gdDiv).on('click', function(e) {
      sound.playCloseButtonSound();
      return $('.gdWrapper').remove();
    });
    gdPlaydivClassName = gameId !== gameInstId ? 'gdResumeDiv' : 'gdPlaydiv';
    gdDiv.append("<div class=\"" + gdPlaydivClassName + "\"></div>");
    if (gameId !== gameInstId) {
      $("." + gdPlaydivClassName, gdDiv).click({
        id: gameId,
        remove: '.gdWrapper'
      }, function(e) {
        sound.playCloseButtonSound();
        if (e.data.remove) {
          $(e.data.remove).remove();
        }
        return jDocument.trigger("gameChangeListener", e.data.id);
      });
    } else {
      $("." + gdPlaydivClassName, gdDiv).on("click", function(e) {
        sound.playCloseButtonSound();
        return $('.gdWrapper').remove();
      });
    }
    i = 0;
    remindUsersData = {};
    for (index in gameDetails.PLSC) {
      plrs = gameDetails.PLRS[gameDetails.PLSC[index]];
      remindUsersData[plrs.PFB] = {
        GSS: plrs.GSS,
        CRS: plrs.CRS
      };
      if (plrs.GSS === 5 || plrs.GSS === 3) {
        continue;
      }
      gdUserImgclassName = (_ref = plrs.PON === 1) != null ? _ref : {
        'gdUserImg user_online': 'gdUserImg'
      };
      _score = plrs.PSC ? plrs.PSC : '0';
      trClass = "userScoreHUD_player";
      betPlacedNoClass = 'userScoreHUD_playerBetPlacedNo arrowclass';
      if (plrs.PDN) {
        playerName = plrs.PDN;
        if (parseInt(plrs.PRE) !== 1) {
          if (parseInt(plrs.PON) === 0) {
            trClass = "userScoreHUD_player GRAY";
          }
        } else {
          if (parseInt(plrs.UI) === parseInt(zzGlobals.currentUserDBId)) {
            playerName = "<s>" + plrs.PDN + "</s>";
            betPlacedNoClass = 'userScoreHUD_playerBetPlacedNo';
          }
        }
      }
      if (plrs.CRS === 9) {
        betPlacedNoClass = 'userScoreHUD_playerBetPlacedNo';
      }
      $('.gdUsersImgdiv', gdDiv).append("<div class=\"gdUserImgDiv user_offline\"><img src=\"" + baseUrl + "/images/zalerio_1.2/4.ingame_ui/carauselbelts_main_player/" + config.userLevelImgBig[parseInt(plrs.PL) - 1] + "\" class=\"gdUserImgbelt\" /><img src=\"https://graph.facebook.com/" + plrs.PFB + "/picture\" class=\"" + gdUserImgclassName + "\" /></div> ");
      $(".gdScoreCardTbl", gdDiv).append("\" <tr class=\"" + trClass + "\">\n	<td  class=\"" + betPlacedNoClass + "\"></td> \n	<td  class=\"userScoreHUD_playerSerial\" >" + (++i) + "</td>\n	<td  class=\"userScoreHUD_playerName\" >" + playerName + "</td>\n	<td class=\"userScoreHUD_playerScore\">" + _score + "</td>\n</tr>");
    }
    $('.gdReminddiv', gdDiv).click({
      gameId: gameId,
      user: remindUsersData
    }, function(e) {
      notifications.remindUsers(e.data.gameId, e.data.user);
    });
    sound.playPopupApperenceSound();
    return $('#active-screen').append(gdDiv);
  };
  jDocument.bind("client:" + zzGlobals.msgCodes.RIGHT_HUD, updateRightHud);
  return true;
});
