// Generated by CoffeeScript 1.3.3

define(["../../config/config", "../../helper/sound"], function(config, sound) {
  var updateRightHud;
  updateRightHud = function(event, message) {
    var gameId, gameSeatID, index, status, urDiv, urDivClassName, _ref;
    for (gameId in message) {
      if (document.getElementById("right_hud_" + gameId) === null) {
        urDivClassName = gameInstId === gameId ? "userArea selected" : "userArea";
        urDiv = $("<div class=\"" + urDivClassName + "\" id=\"right_hud_" + gameId + "\" ></div>");
        if (message[gameId].CR) {
          urDiv.append("<div class=\"round_no\">" + message[gameId].CR + "</div>");
        }
        if (message[gameId].ED) {
          urDiv.append("<div class=\"game_end_time\">" + message[gameId].ED + "</div>");
        }
        for (index in message[gameId].PLSC) {
          gameSeatID = message[gameId].PLSC[index];
          if (message[gameId].PLRS[gameSeatID].GSS === 5 || message[gameId].PLRS[gameSeatID].GSS === 3) {
            continue;
          }
          status = message[gameId].PLRS[gameSeatID].PON === 1 ? "online" : "offline";
          if (message[gameId].PLRS[gameSeatID].PFB) {
            urDiv.append("<div class=\"imageWrapper\" id=\"right_hud_Images" + gameId + "\"><img src=\"https://graph.facebook.com/" + message[gameId].PLRS[gameSeatID].PFB + "/picture\" alt=\"" + message[gameId].PLRS[gameSeatID].PFN + "\" class=\"" + status + "\" id=\"who_am_i_" + gameSeatID + "\" /></div>");
          }
          if (message[gameId].PLRS[gameSeatID].GSS) {
            if (message[gameId].PLRS[gameSeatID].GSS === 1 && zzGlobals.currentUserDBId === message[gameId].PLRS[gameSeatID].UI) {
              urDiv.append("<div class=\"accept_decline\" id=\"accept_decline_" + gameId + "\"><div class=\"right_hud_accept\">Accept</div><div class=\"right_hud_decline\">Decline</div></div>");
              acceptInvitationAdd($("#accept_decline_" + gameId + " .right_hud_accept"), gameId);
              $("#accept_decline_" + gameId + " .right_hud_decline").click({
                gsID: gameSeatID,
                id: gameId
              }, function(e) {
                return jDocument.trigger("sendDeclinedToServer", [e.data.gsID, e.data.id]);
              });
            } else if (zzGlobals.currentUserDBId === message[gameId].PLRS[gameSeatID].UI) {
              urDiv.click({
                id: gameId
              }, function(e) {
                sound.playSelectButtonSound();
                createGameDetailsPopup(e.data.id);
              });
            }
          }
          if (parseInt(message[gameId].GS) === 1) {
            $('#rightHUD-yourturn').append(urDiv);
          }
          if (parseInt(message[gameId].GS) === 2) {
            $('#rightHUD-theirturn').append(urDiv);
          }
        }
      } else {
        if (parseInt(message[gameId].GS) === 0) {
          jQuery("#right_hud_" + gameId).remove();
          continue;
        } else {
          if (parseInt(message[gameId].GS) === 1) {
            if (jQuery("#right_hud_" + gameId).parent().attr('id') === 'rightHUD-theirturn') {
              $("#right_hud_" + gameId).detach().appendTo('#rightHUD-yourturn');
            }
          } else if (parseInt(message[gameId].GS) === 2) {
            if ($("#right_hud_" + gameId).parent().attr('id') === 'rightHUD-yourturn') {
              $("#right_hud_" + gameId).detach().appendTo('#rightHUD-theirturn');
            }
          }
          if (message[gameId].CR) {
            $("#right_hud_" + gameId).find('.round_no').text(message[gameId].CR);
          }
          if (message[gameId].ED) {
            $("#right_hud_" + gameId).find('.game_end_time').html(message[gameId].ED);
          }
          for (gameSeatID in message[gameId].PLRS) {
            if (typeof message[gameId].PLRS[gameSeatID].PON !== "undefined") {
              if (message[gameId].PLRS[gameSeatID].GSS === 5 || message[gameId].PLRS[gameSeatID].GSS === 3) {
                $("#who_am_i_" + gameSeatID).remove();
              } else {
                $("#who_am_i_" + gameSeatID).removeClass().addClass((_ref = message[gameId].PLRS[gameSeatID].PON) != null ? _ref : {
                  "online": "offline"
                });
              }
            }
            if (typeof message[gameId].PLRS[gameSeatID].GSS !== 'undefined') {
              if (message[gameId].PLRS[gameSeatID].GSS !== 1 && zzGlobals.currentUserDBId === message[gameId].PLRS[gameSeatID].UI) {
                $('#accept_decline_' + gameId).remove();
                if (!$("#right_hud_" + gameId).data("events").click) {
                  $("#right_hud_" + gameId).click({
                    id: gameId
                  }, function(e) {
                    sound.playSelectButtonSound();
                    return createGameDetailsPopup(e.data.id);
                  });
                }
              }
            }
          }
        }
      }
    }
    if ($('#rightHUD-yourturn').find(".userArea").length === 0) {
      if ($('#rightHUD-yourturn').find(".newCarouselblanktile").length === 0) {
        $('#rightHUD-yourturn').append('<div class="newCarouselblanktile"></div>');
      }
    } else {
      $("#rightHUD-yourturn .newCarouselblanktile").remove();
    }
    if ($('#rightHUD-theirturn').find(".userArea").length === 0) {
      if ($('#rightHUD-theirturn').find(".newCarouselblanktile").length === 0) {
        $('#rightHUD-theirturn').append('<div class="newCarouselblanktile"></div>');
      }
    } else {
      $("#rightHUD-theirturn .newCarouselblanktile").remove();
    }
    return true;
  };
  window.createGameDetailsPopup = function(gameId) {
    var betPlacedNoClass, gameDetails, gdDiv, gdPlaydivClassName, gdUserImgclassName, i, index, playerName, plrs, remindUsersData, trClass, _ref, _score;
    gameDetails = zzGlobals.msgVars.RH[gameId];
    jQuery('.gdWrapper').remove();
    gdDiv = $("<div class=\"gdWrapper animated fadeInRight\">\n	<div class=\"gdScoreCardDiv\">\n		<div class=\"gdAllRoundDiv\" id=\"gdAllRoundDivId\"></div>\n\n		<div class=\"gdScoreInfoDiv\">\n			<table class=\"gdScoreCardTbl\"></table>\n		</div>\n	</div>\n	<div class=\"gdUsersImgdiv\"></div>\n	<div class=\"gdReminddiv\"></div>\n	<div class=\"gdReturndiv\"></div>\n</div>");
    $('.gdReminddiv', gdDiv).click(function() {
      remindUser(gameId, remindUsersData);
    });
    $('.gdReturndiv', gdDiv).on('click', function(e) {
      sound.playCloseButtonSound();
      return $('.gdWrapper').remove();
    });
    gdPlaydivClassName = gameId !== gameInstId ? 'gdResumeDiv' : 'gdPlaydiv';
    gdDiv.append("<div class=\"" + gdPlaydivClassName + "\"></div>");
    if (gameId !== gameInstId) {
      $("." + gdPlaydivClassName, gdDiv).click({
        id: gameId,
        remove: '.gdWrapper'
      }, function(e) {
        sound.playCloseButtonSound();
        if (e.data.remove) {
          $(e.data.remove).remove();
        }
        return jDocument.trigger("gameChangeListener", e.data.id);
      });
    } else {
      $("." + gdPlaydivClassName, gdDiv).on("click", function(e) {
        sound.playCloseButtonSound();
        return $('.gdWrapper').remove();
      });
    }
    i = 0;
    remindUsersData = {};
    for (index in gameDetails.PLSC) {
      plrs = gameDetails.PLRS[gameDetails.PLSC[index]];
      remindUsersData[plrs.PFB] = {
        GSS: plrs.GSS,
        CRS: plrs.CRS
      };
      if (plrs.GSS === 5 || plrs.GSS === 3) {
        continue;
      }
      gdUserImgclassName = (_ref = plrs.PON === 1) != null ? _ref : {
        'gdUserImg user_online': 'gdUserImg'
      };
      _score = plrs.PSC ? plrs.PSC : '0';
      trClass = "userScoreHUD_player";
      betPlacedNoClass = 'userScoreHUD_playerBetPlacedNo arrowclass';
      if (plrs.PDN) {
        playerName = plrs.PDN;
        if (parseInt(plrs.PRE) !== 1) {
          if (parseInt(plrs.PON) === 0) {
            trClass = "userScoreHUD_player GRAY";
          }
        } else {
          if (parseInt(plrs.UI) === parseInt(zzGlobals.currentUserDBId)) {
            playerName = "<s>" + plrs.PDN + "</s>";
            betPlacedNoClass = 'userScoreHUD_playerBetPlacedNo';
          }
        }
      }
      if (plrs.CRS === 9) {
        betPlacedNoClass = 'userScoreHUD_playerBetPlacedNo';
      }
      $('.gdUsersImgdiv', gdDiv).append("<div class=\"gdUserImgDiv user_offline\"><img src=\"" + baseUrl + "/images/zalerio_1.2/4.ingame_ui/carauselbelts_main_player/" + config.userLevelImgBig[parseInt(plrs.PL) - 1] + "\" class=\"gdUserImgbelt\" /><img src=\"https://graph.facebook.com/" + plrs.PFB + "/picture\" class=\"" + gdUserImgclassName + "\" /></div> ");
      $(".gdScoreCardTbl", gdDiv).append("\" <tr class=\"" + trClass + "\">\n	<td  class=\"" + betPlacedNoClass + "\"></td> \n	<td  class=\"userScoreHUD_playerSerial\" >" + (++i) + "</td>\n	<td  class=\"userScoreHUD_playerName\" >" + playerName + "</td>\n	<td class=\"userScoreHUD_playerScore\">" + _score + "</td>\n</tr>");
    }
    sound.playPopupApperenceSound();
    return $('#active-screen').append(gdDiv);
  };
  jDocument.bind("client:" + zzGlobals.msgCodes.RIGHT_HUD, updateRightHud);
  return true;
});
