// Generated by CoffeeScript 1.3.3

define(['./sound'], function(sound) {
  return window.messagePopup = function(message, callback, callback_param) {
    var msgCancelDiv, msgDiv, msgInnerDiv, msgOkDiv, msgTextDiv, msgTextP;
    jQuery('.msg-outer-div').remove();
    sound.playPopupApperenceSound();
    msgDiv = document.createElement("div");
    msgDiv.className = 'msg-outer-div bounceIn animated';
    msgInnerDiv = document.createElement("div");
    msgInnerDiv.className = 'msg-inner-div';
    msgTextDiv = document.createElement("div");
    msgTextDiv.className = 'msgbox-msg';
    msgTextP = document.createElement("p");
    msgTextP.innerHTML = message;
    msgOkDiv = document.createElement("div");
    msgOkDiv.className = 'msgbox-ok';
    msgOkDiv.innerHTML = 'ok';
    if (typeof callback === 'undefined') {
      msgOkDiv.onclick = function() {
        sound.playCloseButtonSound();
        return jQuery('.msg-outer-div').remove();
      };
    } else {
      msgCancelDiv = document.createElement("div");
      msgCancelDiv.className = 'msgbox-cancel';
      msgCancelDiv.innerHTML = 'cancel';
      msgOkDiv.className = 'msgbox-ok msgbox-cancel';
      msgCancelDiv.onclick = function() {
        sound.playCloseButtonSound();
        return jQuery('.msg-outer-div').remove();
      };
      msgOkDiv.onclick = function() {
        callback(callback_param);
        sound.playCloseButtonSound();
        return jQuery('.msg-outer-div').remove();
      };
    }
    msgTextDiv.appendChild(msgTextP);
    msgInnerDiv.appendChild(msgTextDiv);
    msgInnerDiv.appendChild(msgOkDiv);
    if (msgCancelDiv) {
      msgInnerDiv.appendChild(msgCancelDiv);
    }
    msgDiv.appendChild(msgInnerDiv);
    return jQuery('#active-screen').append(jQuery(msgDiv));
  };
});
