// Generated by CoffeeScript 1.3.3

define([], function() {
  var removeMessagePopup;
  removeMessagePopup = function() {
    sound.playCloseButtonSound();
    $('.overlay').remove();
    return $('.msg-outer-div').remove();
  };
  return window.messagePopup = function(message, callback, callback_param) {
    var popUp;
    removeMessagePopup();
    sound.playPopupApperenceSound();
    popUp = $("<div class=\"overlay\"></div><div class=\"msg-outer-div bounceIn animated\">\n	  					<div class=\"msg-inner-div\"><div class=\"msgbox-msg\"><p>" + message + "</p></div><div class=\"msgbox-ok\">ok</div></div>\n</div>");
    $('.msgbox-ok', popUp).on('click', function(e) {
      return removeMessagePopup()(typeof callback === 'undefined' ? void 0 : $('.msgbox-ok', popUp).on('click', function(e) {
        callback(callback_param);
        return removeMessagePopup();
      }));
    });
    return $('#active-screen').append(popUp);
  };
});
