// Generated by CoffeeScript 1.4.0

define(["./utils"], function(utils) {
  return {
    remindUsers: function(gameId, UsersData, seatId, userData) {
      if (UsersData == null) {
        UsersData = 0;
      }
      return $.ajax({
        type: "POST",
        url: baseUrl + "/user/remindUser",
        data: {
          game_id: gameId,
          user_data: UsersData,
          lh_users_data: userData
        },
        success: function(responseData, textStatus, jqXHR) {
          if (responseData) {
            return FB.ui({
              method: 'apprequests',
              message: 'You are invited to play a game of zalerio',
              to: responseData
            }, function(response) {
              if (response) {
                return messagePopup(popupMSG.remindSucess(''));
              } else {
                return utils.log("notificatoion send fail : " + responseData + "\n errorThrown : " + errorThrown);
              }
            });
          } else {
            return messagePopup(popupMSG.remindSucess(''));
          }
        },
        error: function(responseData, textStatus, errorThrown) {
          return utils.log("notificatoion send fail : " + responseData + "\n errorThrown : " + errorThrown);
        }
      });
    }
  };
});
