// Generated by CoffeeScript 1.3.3

define(["./utils"], function(utils) {
  return {
    remindUsers: function(gameId, UsersData, seatId, userData) {
      if (UsersData == null) {
        UsersData = 0;
      }
      return $.ajax({
        type: "POST",
        url: baseUrl + "/user/remindUser",
        data: {
          game_id: gameId,
          user_data: UsersData,
          lh_users_data: userData
        },
        success: function(responseData, textStatus, jqXHR) {
          return messagePopup(popupMSG.remindSucess(''));
        },
        error: function(responseData, textStatus, errorThrown) {
          return utils.log("notificatoion send fail : " + responseData + "\n errorThrown : " + errorThrown);
        }
      });
    }
  };
});
