// Generated by CoffeeScript 1.4.0

define([], function() {
  var Sound;
  Sound = (function() {

    function Sound() {
      try {
        this.audioBaseUrl = baseUrl.replace('/index.php', '/');
        this.otherButton = new Audio(this.audioBaseUrl + "/sound/otherbuttons.wav");
        this.selectButton = new Audio(this.audioBaseUrl + "/sound/select_button.wav");
        this.popupApperence = new Audio(this.audioBaseUrl + "/sound/popupapperence.wav");
        this.closeButton = new Audio(this.audioBaseUrl + "/sound/closebutton.wav");
        this.tilePickup = new Audio(this.audioBaseUrl + "/sound/Tilepickup.wav");
        this.titleDrop = new Audio(baseUrl + "/sound/Tiledrop.wav");
        this.playButton = new Audio(baseUrl + "/sound/playbutton.wav");
        this.isPlaySound = true;
        this.isError = false;
        window.isError = false;
      } catch (err) {
        this.isPlaySound = false;
        this.isError = true;
        window.isError = true;
        window.playSound = false;
      }
    }

    Sound.prototype.onSound = function() {
      if (!this.isError) {
        return this.isPlaySound = true;
      }
    };

    Sound.prototype.offSound = function() {
      return this.isPlaySound = false;
    };

    Sound.prototype.playOtherButtonSound = function() {
      if (this.isPlaySound) {
        return this.otherButton.play();
      }
    };

    Sound.prototype.playSelectButtonSound = function() {
      if (this.isPlaySound) {
        return this.selectButton.play();
      }
    };

    Sound.prototype.playPopupApperenceSound = function() {
      if (this.isPlaySound) {
        return this.popupApperence.play();
      }
    };

    Sound.prototype.playCloseButtonSound = function() {
      if (this.isPlaySound) {
        return this.closeButton.play();
      }
    };

    Sound.prototype.playTilePickupSound = function() {
      if (this.isPlaySound) {
        return this.tilePickup.play();
      }
    };

    Sound.prototype.playTitleDropSound = function() {
      if (this.isPlaySound) {
        return this.titleDrop.play();
      }
    };

    Sound.prototype.playPlayButtonSound = function() {
      if (this.isPlaySound) {
        return this.playButton.play();
      }
    };

    return Sound;

  })();
  return window.sound = new Sound;
});
