// Generated by CoffeeScript 1.3.3

define([], function() {
  return {
    addEventHandler: function(node, evtType, func, isCapture) {
      if (window && window.addEventListener) {
        return node.addEventListener(evtType, func, isCapture);
      } else {
        return node.attachEvent("on" + evtType, func);
      }
    },
    removeEventHandler: function(node, evtType, func, isCapture) {
      if (window && window.removeEventListener) {
        return node.removeEventListener(evtType, func, isCapture);
      } else {
        return node.detachEvent("on" + evtType, func);
      }
    },
    removeClassName: function(node, cls) {
      var reg;
      reg = void 0;
      if ((node != null) && node.className) {
        reg = new RegExp("(\\s|^)" + cls + "(\\s|$)");
        return node.className = node.className.replace(reg, " ");
      }
    },
    log: function(message) {
      return console.log(message);
    },
    getMiniLoaderHTML: function() {
      return "<div id=\"floatingBarsGs\">\n<div class=\"blockG\" id=\"rotateG_01\">\n</div>\n<div class=\"blockG\" id=\"rotateG_02\">\n</div>\n<div class=\"blockG\" id=\"rotateG_03\">\n</div>\n<div class=\"blockG\" id=\"rotateG_04\">\n</div>\n<div class=\"blockG\" id=\"rotateG_05\">\n</div>\n<div class=\"blockG\" id=\"rotateG_06\">\n</div>\n<div class=\"blockG\" id=\"rotateG_07\">\n</div>\n<div class=\"blockG\" id=\"rotateG_08\">\n</div>\n</div>";
    }
  };
});
