/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzgame extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzgameRecord> {

	private static final long serialVersionUID = -1374361090;

	/**
	 * The singleton instance of zzgame
	 */
	public static final net.user1.union.zz.common.model.tables.Zzgame ZZGAME = new net.user1.union.zz.common.model.tables.Zzgame();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzgameRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzgameRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzgameRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameRecord, java.lang.String> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameRecord, java.lang.String> GAME_NAME = createField("game_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzgame() {
		super("zzgame", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzgame(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzgame.ZZGAME);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzgame_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameRecord>>asList(net.user1.union.zz.common.model.Keys.zzgame_pkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzgame as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzgame(alias);
	}
}
