/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzinvitefriends extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord> {

	private static final long serialVersionUID = 1354616392;

	/**
	 * The singleton instance of zzinvitefriends
	 */
	public static final net.user1.union.zz.common.model.tables.Zzinvitefriends ZZINVITEFRIENDS = new net.user1.union.zz.common.model.tables.Zzinvitefriends();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord, java.lang.Long> FBID = createField("fbid", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord, java.lang.String> ZZINVITEFRIENDS_STATUS = createField("zzinvitefriends_status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * No further instances allowed
	 */
	private Zzinvitefriends() {
		super("zzinvitefriends", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzinvitefriends(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzinvitefriends.ZZINVITEFRIENDS);
	}

//	@Override
////	public org.jooq.Identity<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord, java.lang.String> getIdentity() {
////		return net.user1.union.zz.common.model.Keys.IDENTITY_zzinvitefriends;
////	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.id;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzinvitefriendsRecord>>asList(net.user1.union.zz.common.model.Keys.id);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzinvitefriends as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzinvitefriends(alias);
	}
}
