/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Authassignment extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord> {

	private static final long serialVersionUID = 1198255867;

	/**
	 * The singleton instance of authassignment
	 */
	public static final net.user1.union.zz.common.model.tables.Authassignment AUTHASSIGNMENT = new net.user1.union.zz.common.model.tables.Authassignment();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.AuthassignmentRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.authassignment.itemname]
	 * REFERENCES authitem [public.authitem.name]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, java.lang.String> ITEMNAME = createField("itemname", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, java.lang.String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, java.lang.String> BIZRULE = createField("bizrule", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, java.lang.String> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Authassignment() {
		super("authassignment", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Authassignment(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Authassignment.AUTHASSIGNMENT);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.authassignment_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord>>asList(net.user1.union.zz.common.model.Keys.authassignment_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.AuthassignmentRecord, ?>>asList(net.user1.union.zz.common.model.Keys.authassignment_itemname_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Authassignment as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Authassignment(alias);
	}
}
