/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzgameseat extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord> {

	private static final long serialVersionUID = -750897887;

	/**
	 * The singleton instance of zzgameseat
	 */
	public static final net.user1.union.zz.common.model.tables.Zzgameseat ZZGAMESEAT = new net.user1.union.zz.common.model.tables.Zzgameseat();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzgameseatRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.lang.String> GAMESEAT_ID = createField("gameseat_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.lang.String> GAMESEAT_USER_ID = createField("gameseat_user_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameseat.gameseat_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.lang.String> GAMESEAT_GAMEINST_ID = createField("gameseat_gameinst_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.sql.Timestamp> GAMESEAT_CREATEDAT = createField("gameseat_createdat", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.lang.Integer> GAME_RANK = createField("game_rank", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.lang.String> ZZGAMESEAT_STATUS = createField("zzgameseat_status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.lang.Integer> GAMESEAT_SCORE = createField("gameseat_score", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, java.sql.Timestamp> GAMESEAT_STATUS_UPDATE_TIME = createField("gameseat_status_update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzgameseat() {
		super("zzgameseat", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzgameseat(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzgameseat_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord>>asList(net.user1.union.zz.common.model.Keys.zzgameseat_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzgameseatRecord, ?>>asList(net.user1.union.zz.common.model.Keys.zzgameseat_gameseat_user_id_fkey, net.user1.union.zz.common.model.Keys.zzgameseat_gameseat_gameinst_id_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzgameseat as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzgameseat(alias);
	}
}
