/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzgameinsttempl extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord> {

	private static final long serialVersionUID = 558611347;

	/**
	 * The singleton instance of zzgameinsttempl
	 */
	public static final net.user1.union.zz.common.model.tables.Zzgameinsttempl ZZGAMEINSTTEMPL = new net.user1.union.zz.common.model.tables.Zzgameinsttempl();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINSTTEMPL_ID = createField("gameinsttempl_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzgameinsttempl.gameinsttempl_game_id]
	 * REFERENCES zzgame [public.zzgame.game_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINSTTEMPL_GAME_ID = createField("gameinsttempl_game_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINSTTEMPL_GAME_DESC = createField("gameinsttempl_game_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM1 = createField("gameinst_paramnum1", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM2 = createField("gameinst_paramnum2", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM3 = createField("gameinst_paramnum3", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM4 = createField("gameinst_paramnum4", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM5 = createField("gameinst_paramnum5", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM6 = createField("gameinst_paramnum6", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM7 = createField("gameinst_paramnum7", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM8 = createField("gameinst_paramnum8", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM9 = createField("gameinst_paramnum9", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.Integer> GAMEINST_PARAMNUM10 = createField("gameinst_paramnum10", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.sql.Timestamp> GAMEINST_PARAMDATE1 = createField("gameinst_paramdate1", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.sql.Timestamp> GAMEINST_PARAMDATE2 = createField("gameinst_paramdate2", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.sql.Timestamp> GAMEINST_PARAMDATE3 = createField("gameinst_paramdate3", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.sql.Timestamp> GAMEINST_PARAMDATE4 = createField("gameinst_paramdate4", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.sql.Timestamp> GAMEINST_PARAMDATE5 = createField("gameinst_paramdate5", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINST_PARAMVAR1 = createField("gameinst_paramvar1", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINST_PARAMVAR2 = createField("gameinst_paramvar2", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINST_PARAMVAR3 = createField("gameinst_paramvar3", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINST_PARAMVAR4 = createField("gameinst_paramvar4", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.lang.String> GAMEINST_PARAMVAR5 = createField("gameinst_paramvar5", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzgameinsttempl() {
		super("zzgameinsttempl", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzgameinsttempl(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzgameinsttempl.ZZGAMEINSTTEMPL);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzgameinsttempl_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord>>asList(net.user1.union.zz.common.model.Keys.zzgameinsttempl_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzgameinsttemplRecord, ?>>asList(net.user1.union.zz.common.model.Keys.zzgameinsttempl_gameinsttempl_game_id_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzgameinsttempl as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzgameinsttempl(alias);
	}
}
