/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzproduct extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzproductRecord> {

	private static final long serialVersionUID = 839271277;

	/**
	 * The singleton instance of zzproduct
	 */
	public static final net.user1.union.zz.common.model.tables.Zzproduct ZZPRODUCT = new net.user1.union.zz.common.model.tables.Zzproduct();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzproductRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzproductRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzproductRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.lang.String> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.lang.String> PRODUCT_SKU = createField("product_sku", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.lang.String> PRODUCT_NAME = createField("product_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.lang.String> PRODUCT_BRAND = createField("product_brand", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.lang.String> PRODUCT_SHORTDESC = createField("product_shortdesc", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.lang.String> PRODUCT_IMAGENAME = createField("product_imagename", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.lang.String> PRODUCT_DESC = createField("product_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.math.BigDecimal> PRODUCT_PRICE = createField("product_price", org.jooq.impl.SQLDataType.NUMERIC, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzproductRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzproduct() {
		super("zzproduct", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzproduct(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzproduct.ZZPRODUCT);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzproductRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzproduct_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzproductRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzproductRecord>>asList(net.user1.union.zz.common.model.Keys.zzproduct_pkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzproduct as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzproduct(alias);
	}
}
