/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzzlrogamescore extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord> {

	private static final long serialVersionUID = 1633484947;

	/**
	 * The singleton instance of zzzlrogamescore
	 */
	public static final net.user1.union.zz.common.model.tables.Zzzlrogamescore ZZZLROGAMESCORE = new net.user1.union.zz.common.model.tables.Zzzlrogamescore();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, java.lang.String> ZLGAMESCORE_ID = createField("zlgamescore_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, java.lang.String> ZLGAMESCORE_ZLGAMEROUND_ID = createField("zlgamescore_zlgameround_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, java.lang.String> ZLGAMESCORE_GAMESEAT_ID = createField("zlgamescore_gameseat_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, java.lang.Integer> ZLGAMESCORE_SCORED = createField("zlgamescore_scored", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzzlrogamescore() {
		super("zzzlrogamescore", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzzlrogamescore(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzzlrogamescore_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord>>asList(net.user1.union.zz.common.model.Keys.zzzlrogamescore_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord, ?>>asList(net.user1.union.zz.common.model.Keys.zzzlrogamescore_zlgamescore_zlgameround_id_fkey, net.user1.union.zz.common.model.Keys.zzzlrogamescore_zlgamescore_gameseat_id_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzzlrogamescore as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzzlrogamescore(alias);
	}
}
