/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzzlrofriends extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord> {

	private static final long serialVersionUID = -835503504;

	/**
	 * The singleton instance of zzzlrofriends
	 */
	public static final net.user1.union.zz.common.model.tables.Zzzlrofriends ZZZLROFRIENDS = new net.user1.union.zz.common.model.tables.Zzzlrofriends();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofriends.user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord, java.lang.String> FRIEND_ID = createField("friend_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * No further instances allowed
	 */
	private Zzzlrofriends() {
		super("zzzlrofriends", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzzlrofriends(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzzlrofriends_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord>>asList(net.user1.union.zz.common.model.Keys.zzzlrofriends_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord, ?>>asList(net.user1.union.zz.common.model.Keys.zzzlrofriends_user_id_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzzlrofriends as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzzlrofriends(alias);
	}
}
