/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzzlrogameinstfig extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord> {

	private static final long serialVersionUID = -1218246820;

	/**
	 * The singleton instance of zzzlrogameinstfig
	 */
	public static final net.user1.union.zz.common.model.tables.Zzzlrogameinstfig ZZZLROGAMEINSTFIG = new net.user1.union.zz.common.model.tables.Zzzlrogameinstfig();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, java.lang.String> ZLGAMEINSTFIG_ID = createField("zlgameinstfig_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, java.lang.String> ZLGAMEINSTFIG_ZLFIGINST_ID = createField("zlgameinstfig_zlfiginst_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, java.lang.String> ZLGAMEINSTFIG_GAMEINST_ID = createField("zlgameinstfig_gameinst_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, java.lang.Integer> ZLGAMEINSTFIG_POSLEFT = createField("zlgameinstfig_posleft", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, java.lang.Integer> ZLGAMEINSTFIG_POSTOP = createField("zlgameinstfig_postop", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzzlrogameinstfig() {
		super("zzzlrogameinstfig", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzzlrogameinstfig(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzzlrogameinstfig_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord>>asList(net.user1.union.zz.common.model.Keys.zzzlrogameinstfig_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord, ?>>asList(net.user1.union.zz.common.model.Keys.zzzlrogameinstfig_zlgameinstfig_zlfiginst_id_fkey, net.user1.union.zz.common.model.Keys.zzzlrogameinstfig_zlgameinstfig_gameinst_id_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzzlrogameinstfig as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzzlrogameinstfig(alias);
	}
}
