/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzzlrofiginstcoord extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord> {

	private static final long serialVersionUID = 590786084;

	/**
	 * The singleton instance of zzzlrofiginstcoord
	 */
	public static final net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord ZZZLROFIGINSTCOORD = new net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, java.lang.String> ZLFIGINSTCOORD_ID = createField("zlfiginstcoord_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofiginstcoord.zlfiginstcoord_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, java.lang.String> ZLFIGINSTCOORD_ZLFIGINST_ID = createField("zlfiginstcoord_zlfiginst_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, java.lang.Integer> ZLFIGINSTCOORD_POSX = createField("zlfiginstcoord_posx", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, java.lang.Integer> ZLFIGINSTCOORD_POSY = createField("zlfiginstcoord_posy", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzzlrofiginstcoord() {
		super("zzzlrofiginstcoord", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzzlrofiginstcoord(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord.ZZZLROFIGINSTCOORD);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzzlrofiginstcoord_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord>>asList(net.user1.union.zz.common.model.Keys.zzzlrofiginstcoord_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrofiginstcoordRecord, ?>>asList(net.user1.union.zz.common.model.Keys.zzzlrofiginstcoord_zlfiginstcoord_zlfiginst_id_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzzlrofiginstcoord(alias);
	}
}
