// Generated by CoffeeScript 1.4.0

define(['zalzero.utils', 'zalzero.config'], function(utils, config) {
  var _arrow, _arrow_right, _def, _finish, _initialize, _popup, _startGameButtonClick;
  _def = null;
  _popup = null;
  _arrow = null;
  _arrow_right = null;
  _startGameButtonClick = function(e) {
    _finish();
    return false;
  };
  _initialize = function(args, def) {
    _def = def;
    utils.addHighlight('#startButton');
    utils.addPositionRelative('#startButton');
    if (window.secondArrow === '0') {
      _arrow = utils.createArrow(190, 100, 'right');
    } else {
      _arrow_right = utils.createArrow(540, 100, 'left');
      _arrow = utils.createArrow(190, 100, 'right');
      $('#rightHUDbackground').addClass('tutorial-highlight');
    }
    utils.congratPopup();
    $('#startButton').on('click', _startGameButtonClick);
    $('#rightHUDbackground').on('click', _startGameButtonClick);
    return true;
  };
  _finish = function() {
    utils.removeHighlight('#startButton');
    $('#startButton').off('click', _startGameButtonClick);
    $('#rightHUDbackground').off('click', _startGameButtonClick);
    _arrow.remove();
    _arrow_right.remove();
    utils.removeHighlight('#rightHUDbackground');
    _def.resolve();
    return true;
  };
  return {
    chainFunc: function(arg, def) {
      _initialize(null, def);
      return true;
    }
  };
});
