// Generated by CoffeeScript 1.3.3

define([], function() {
  return {
    POPUP_MESSAGE_BEFORE_INIT_TEXT_POINT: "The one who uncovers the most valuable objects wins!\n  		<ul>\n<li>	fun game for 2-5 players	</li>\n<li>	play over 7 rounds	</li>\n<li>	place titles that uncover objects	</li>\n<li>	play multiple games at same time	</li>\n<li>	strategy game that needs some smarts and skills. Easy to learn! </li></ul>",
    POPUP_MESSAGE_STEP_1: "Check out the Numbers hidden in the Matrix and then press 'BACK TO GAME' button.",
    POPUP_MESSAGE_STEP_2: "Place the tile to figure out the patterns of Numbers which are hidden in the matrix.",
    POPUP_MESSAGE_STEP_3: "After you place all tiles, press the 'PLAY' button and wait for your friends to place their tiles.",
    POPUP_MESSAGE_STEP_4: "The tiles which you placed correctly will be green, your wrong tiles will be orange, while other players wrong tiles are grey.",
    POPUP_MESSAGE_STEP_5: "Now its time for you to enjoy the game. Hit 'Start a Game' button to play with your friends. ",
    POPUP_MESSAGE_CONGRATULATION: "You are done with our short tutorial!\n<br>\n\n  		<ul>\n	You find always more help at \n	<li>	Cheat Sheet	</li>\n	<li>	Help Section </li>\n</ul>",
    BETS_ARR: [
      {
        id: 'boardTile-3',
        className: 'box-currentRoundCorrect',
        content: '1',
        showFirst: true
      }, {
        id: 'boardTile-30',
        className: 'box-currentRoundIncorrect',
        content: '',
        showFirst: true
      }, {
        id: 'boardTile-100',
        className: 'box-currentRoundCorrect',
        content: '1',
        showFirst: true
      }, {
        id: 'boardTile-121',
        className: 'box-currentRoundCorrect',
        content: '1',
        showFirst: true
      }, {
        id: 'boardTile-154',
        className: 'box-currentRoundIncorrect',
        content: '',
        showFirst: true
      }, {
        id: 'boardTile-160',
        className: 'box-currentRoundCorrect',
        content: '2',
        showFirst: true
      }, {
        id: 'boardTile-201',
        className: 'box-currentRoundIncorrect',
        content: '',
        showFirst: true
      }, {
        id: 'boardTile-251',
        className: 'box-currentRoundCorrect',
        content: '1',
        showFirst: true
      }, {
        id: 'boardTile-223',
        className: 'box-previousRoundOtherPlayer',
        content: '',
        showFirst: false
      }, {
        id: 'boardTile-224',
        className: 'box-previousRoundOtherPlayer',
        content: '',
        showFirst: false
      }, {
        id: 'boardTile-250',
        className: 'box-previousRoundOtherPlayer',
        content: '',
        showFirst: false
      }
    ]
  };
});
