// Generated by CoffeeScript 1.4.0

define(['zalzero.utils', 'zalzero.config'], function(utils, config) {
  var _arrow, _backToTheGameClick, _cheatSheetClick, _def, _finish, _initialize, _popup;
  _arrow = null;
  _def = null;
  _popup = null;
  _cheatSheetClick = function(e) {
    var scrollApi, _glassLayer;
    _arrow.remove();
    _glassLayer = $('<div id="glass_layer" style="position:fixed;top:0;bottom:0;right:0px;left:0px;z-index:1002"></div>');
    $('body').append(_glassLayer);
    _glassLayer.on('click', function(e) {
      return false;
    });
    $(".popup-cheatsheet .jspPane").css('top', '0px');
    $(".popup-cheatsheet .jspDrag").css('top', '0px');
    scrollApi = $('.popup-cheatsheet').data('jsp');
    scrollApi.reinitialise({
      animateDuration: 8500
    });
    setTimeout((function() {
      $('#glass_layer').remove();
      _popup = utils.createPopup(200, 200, config.POPUP_MESSAGE_STEP_1, function(e) {
        return false;
      });
      $('#cheat-sheet').off('click', _cheatSheetClick);
      $('#cheat-sheet').on('click', _backToTheGameClick);
      _arrow = utils.createArrow(225, 0, 'top');
      return true;
    }), 8500);
    scrollApi.scrollToBottom(true);
    return true;
  };
  _backToTheGameClick = function(e) {
    return _finish();
  };
  _initialize = function(args, def) {
    _def = def;
    utils.addHighlight('.friendChallenge', '.popup-cheatsheet');
    _arrow = utils.createArrow(225, 0, 'top');
    $('#cheat-sheet').on('click', _cheatSheetClick);
    return true;
  };
  _finish = function() {
    utils.removeHighlight('.friendChallenge', '.popup-cheatsheet');
    _arrow.remove();
    $('#cheat-sheet').off('click', _cheatSheetClick);
    $('#cheat-sheet').off('click', _backToTheGameClick);
    return _def.resolve();
  };
  return {
    chainFunc: function(arg, def) {
      _initialize(null, def);
      return true;
    }
  };
});
