// Generated by CoffeeScript 1.3.3

define(['zalzero.utils', 'zalzero.config'], function(utils, config) {
  var _arrow, _def, _finish, _initialize, _popup, _startGameButtonClick;
  _def = null;
  _popup = null;
  _arrow = null;
  _startGameButtonClick = function(e) {
    _finish();
    return false;
  };
  _initialize = function(args, def) {
    _def = def;
    utils.addHighlight('#startButton');
    utils.addPositionRelative('#startButton');
    utils.activateAccordion(4);
    _arrow = utils.createArrow(190, 100, 'right');
    _popup = utils.createPopup(200, 200, config.POPUP_MESSAGE_STEP_5, function(e) {
      return false;
    });
    $('#startButton').on('click', _startGameButtonClick);
    return true;
  };
  _finish = function() {
    utils.removeHighlight('#startButton');
    $('#startButton').off('click', _startGameButtonClick);
    _arrow.remove();
    _def.resolve();
    return true;
  };
  return {
    chainFunc: function(arg, def) {
      _initialize(null, def);
      return true;
    }
  };
});
