// Generated by CoffeeScript 1.4.0

define(['zalzero.utils', 'zalzero.config'], function(utils, config) {
  var _arrow, _arrow_right, _def, _finish, _initialize, _popup, _startGameButtonClick;
  _def = null;
  _popup = null;
  _arrow = null;
  _arrow_right = null;
  _startGameButtonClick = function(e) {
    _finish();
    return false;
  };
  _initialize = function(args, def) {
    _def = def;
    utils.congratPopup();
    $('.finish').on('click', _startGameButtonClick);
    return true;
  };
  _finish = function() {
    $('.finish').off('click', _startGameButtonClick);
    $('.popup-wrapper').remove();
    $('.gameInfoPanel').css('display', 'block');
    $('.gameScore').css('display', 'block');
    $('#tutorial-accordion').css('display', 'none');
    _def.resolve();
    return true;
  };
  return {
    chainFunc: function(arg, def) {
      _initialize(null, def);
      return true;
    }
  };
});
