// Generated by CoffeeScript 1.4.0

define(['zalzero.utils', 'zalzero.config'], function(utils, config) {
  var _arrow, _def, _finish, _initialize, _playButtonClick, _popup;
  _def = null;
  _arrow = null;
  _popup = null;
  _playButtonClick = function(e) {
    _finish();
    return false;
  };
  _initialize = function(args, def) {
    _def = def;
    utils.activateAccordion(2);
    _popup = utils.createPopup(200, 200, config.POPUP_MESSAGE_STEP_3, function(e) {
      _arrow = utils.createArrow(512, 480, 'top');
      $('#bottomHUDbuttons-play').removeClass();
      utils.addHighlight('#placeBetOnServer');
      utils.addPositionRelative('#placeBetOnServer');
      $('#placeBetOnServer').on('click', _playButtonClick);
      return false;
    });
    return true;
  };
  _finish = function() {
    utils.removeHighlight('#placeBetOnServer');
    _arrow.remove();
    $('#placeBetOnServer').off('click', _playButtonClick);
    _def.resolve();
    return true;
  };
  return {
    chainFunc: function(arg, def) {
      _initialize(null, def);
      return true;
    }
  };
});
