/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Authitemchild extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord> {

	private static final long serialVersionUID = -1555645331;

	/**
	 * The singleton instance of authitemchild
	 */
	public static final net.user1.union.zz.common.model.tables.Authitemchild AUTHITEMCHILD = new net.user1.union.zz.common.model.tables.Authitemchild();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.AuthitemchildRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.authitemchild.parent]
	 * REFERENCES authitem [public.authitem.name]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord, java.lang.String> PARENT = createField("parent", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.authitemchild.child]
	 * REFERENCES authitem [public.authitem.name]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord, java.lang.String> CHILD = createField("child", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Authitemchild() {
		super("authitemchild", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Authitemchild(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Authitemchild.AUTHITEMCHILD);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.authitemchild_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord>>asList(net.user1.union.zz.common.model.Keys.authitemchild_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.AuthitemchildRecord, ?>>asList(net.user1.union.zz.common.model.Keys.authitemchild_parent_fkey, net.user1.union.zz.common.model.Keys.authitemchild_child_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Authitemchild as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Authitemchild(alias);
	}
}
