/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Roles extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.RolesRecord> {

	private static final long serialVersionUID = -871926639;

	/**
	 * The singleton instance of roles
	 */
	public static final net.user1.union.zz.common.model.tables.Roles ROLES = new net.user1.union.zz.common.model.tables.Roles();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.RolesRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.RolesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.RolesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.RolesRecord, java.lang.String> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.RolesRecord, java.lang.String> ROLE_NAME = createField("role_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.RolesRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.RolesRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Roles() {
		super("roles", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Roles(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Roles.ROLES);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.RolesRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.roles_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.RolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.RolesRecord>>asList(net.user1.union.zz.common.model.Keys.roles_pkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Roles as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Roles(alias);
	}
}
