/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class Zzzlrogamebet extends org.jooq.impl.UpdatableTableImpl<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord> {

	private static final long serialVersionUID = 1178577611;

	/**
	 * The singleton instance of zzzlrogamebet
	 */
	public static final net.user1.union.zz.common.model.tables.Zzzlrogamebet ZZZLROGAMEBET = new net.user1.union.zz.common.model.tables.Zzzlrogamebet();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord> __RECORD_TYPE = net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, java.lang.String> ZLGAMEBET_ID = createField("zlgamebet_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, java.lang.String> ZLGAMEBET_ZLGAMEROUND_ID = createField("zlgamebet_zlgameround_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamebet.zlgamebet_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, java.lang.String> ZLGAMEBET_GAMESEAT_ID = createField("zlgamebet_gameseat_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, java.sql.Timestamp> ZLGAMEBET_BETTIME = createField("zlgamebet_bettime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, java.lang.Integer> ZLGAMEBET_BETCOORD = createField("zlgamebet_betcoord", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * No further instances allowed
	 */
	private Zzzlrogamebet() {
		super("zzzlrogamebet", net.user1.union.zz.common.model.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Zzzlrogamebet(java.lang.String alias) {
		super(alias, net.user1.union.zz.common.model.Public.PUBLIC, net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET);
	}

	@Override
	public org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord> getMainKey() {
		return net.user1.union.zz.common.model.Keys.zzzlrogamebet_pkey;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord>>asList(net.user1.union.zz.common.model.Keys.zzzlrogamebet_pkey);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord, ?>>asList(net.user1.union.zz.common.model.Keys.zzzlrogamebet_zlgamebet_zlgameround_id_fkey, net.user1.union.zz.common.model.Keys.zzzlrogamebet_zlgamebet_gameseat_id_fkey);
	}

	@Override
	public net.user1.union.zz.common.model.tables.Zzzlrogamebet as(java.lang.String alias) {
		return new net.user1.union.zz.common.model.tables.Zzzlrogamebet(alias);
	}
}
