/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrogameinstfigRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrogameinstfigRecord> {

	private static final long serialVersionUID = -1678078206;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlgameinstfigId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlgameinstfigId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public void setZlgameinstfigZlfiginstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_ZLFIGINST_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public java.lang.String getZlgameinstfigZlfiginstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_ZLFIGINST_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_zlfiginst_id]
	 * REFERENCES zzzlrofiginst [public.zzzlrofiginst.zlfiginst_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzzlrofiginstRecord fetchZzzlrofiginst() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST)
			.where(net.user1.union.zz.common.model.tables.Zzzlrofiginst.ZZZLROFIGINST.ZLFIGINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_ZLFIGINST_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public void setZlgameinstfigGameinstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_GAMEINST_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public java.lang.String getZlgameinstfigGameinstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_GAMEINST_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameinstfig.zlgameinstfig_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameinstRecord fetchZzgameinst() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_GAMEINST_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setZlgameinstfigPosleft(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_POSLEFT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlgameinstfigPosleft() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_POSLEFT);
	}

	/**
	 * An uncommented item
	 */
	public void setZlgameinstfigPostop(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_POSTOP, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlgameinstfigPostop() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.ZLGAMEINSTFIG_POSTOP);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrogameinstfigRecord
	 */
	public ZzzlrogameinstfigRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrogameinstfig.ZZZLROGAMEINSTFIG);
	}
}
