/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrogamescoreRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord> {

	private static final long serialVersionUID = 2099745274;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlgamescoreId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlgamescoreId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public void setZlgamescoreZlgameroundId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_ZLGAMEROUND_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public java.lang.String getZlgamescoreZlgameroundId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_ZLGAMEROUND_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_zlgameround_id]
	 * REFERENCES zzzlrogameround [public.zzzlrogameround.zlgameround_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzzlrogameroundRecord fetchZzzlrogameround() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND)
			.where(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_ZLGAMEROUND_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public void setZlgamescoreGameseatId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_GAMESEAT_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public java.lang.String getZlgamescoreGameseatId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_GAMESEAT_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogamescore.zlgamescore_gameseat_id]
	 * REFERENCES zzgameseat [public.zzgameseat.gameseat_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameseatRecord fetchZzgameseat() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT)
			.where(net.user1.union.zz.common.model.tables.Zzgameseat.ZZGAMESEAT.GAMESEAT_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_GAMESEAT_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setZlgamescoreScored(java.lang.Integer value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_SCORED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getZlgamescoreScored() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_SCORED);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrogamescoreRecord
	 */
	public ZzzlrogamescoreRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE);
	}
}
