/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrofriendsRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrofriendsRecord> {

	private static final long serialVersionUID = 654969562;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofriends.user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public void setUserId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS.USER_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofriends.user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public java.lang.String getUserId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS.USER_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrofriends.user_id]
	 * REFERENCES zzuser [public.zzuser.user_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzuserRecord fetchZzuser() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER)
			.where(net.user1.union.zz.common.model.tables.Zzuser.ZZUSER.USER_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS.USER_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setFriendId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS.FRIEND_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getFriendId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS.FRIEND_ID);
	}

	/**
	 * Create a detached ZzzlrofriendsRecord
	 */
	public ZzzlrofriendsRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrofriends.ZZZLROFRIENDS);
	}
}
