/**
 * This class is generated by jOOQ
 */
package net.user1.union.zz.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class ZzzlrogameroundRecord extends org.jooq.impl.UpdatableRecordImpl<net.user1.union.zz.common.model.tables.records.ZzzlrogameroundRecord> {

	private static final long serialVersionUID = 372047833;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setZlgameroundId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.String getZlgameroundId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrogamebetRecord> fetchZzzlrogamebetList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET)
			.where(net.user1.union.zz.common.model.tables.Zzzlrogamebet.ZZZLROGAMEBET.ZLGAMEBET_ZLGAMEROUND_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<net.user1.union.zz.common.model.tables.records.ZzzlrogamescoreRecord> fetchZzzlrogamescoreList() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE)
			.where(net.user1.union.zz.common.model.tables.Zzzlrogamescore.ZZZLROGAMESCORE.ZLGAMESCORE_ZLGAMEROUND_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameround.zlgameround_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public void setZlgameroundGameinstId(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_GAMEINST_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameround.zlgameround_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public java.lang.String getZlgameroundGameinstId() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_GAMEINST_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [public.zzzlrogameround.zlgameround_gameinst_id]
	 * REFERENCES zzgameinst [public.zzgameinst.gameinst_id]
	 * </pre></code>
	 */
	public net.user1.union.zz.common.model.tables.records.ZzgameinstRecord fetchZzgameinst() {
		return create()
			.selectFrom(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST)
			.where(net.user1.union.zz.common.model.tables.Zzgameinst.ZZGAMEINST.GAMEINST_ID.equal(getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_GAMEINST_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setZlgameroundRoundname(java.lang.String value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ROUNDNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getZlgameroundRoundname() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_ROUNDNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setZlgameroundTimestart(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_TIMESTART, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getZlgameroundTimestart() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_TIMESTART);
	}

	/**
	 * An uncommented item
	 */
	public void setZlgameroundTimeend(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_TIMEEND, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getZlgameroundTimeend() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.ZLGAMEROUND_TIMEEND);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getUpdateTime() {
		return getValue(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND.UPDATE_TIME);
	}

	/**
	 * Create a detached ZzzlrogameroundRecord
	 */
	public ZzzlrogameroundRecord() {
		super(net.user1.union.zz.common.model.tables.Zzzlrogameround.ZZZLROGAMEROUND);
	}
}
